### ISSUE TITLE
It seem didn't support Chinese characters?

### ISSUE THREAD

**Issue by naxiemolv** [thecodingmachine/gotenberg#10]

**Comment by gulien** [comment]
Hello @naxiemolv 

I guess you have to update the Dockerfile in order to support Chinese characters.

**Comment by naxiemolv** [comment]
got it, thank you!

**Comment by zhedream** [comment]
> 收到了。谢谢！



> got it, thank you!

Hello, I met this problem, but I'm not familiar with docker. Can you tell me how to solve it?
