### ISSUE TITLE
Need add command "fc-cache -f -v"

### ISSUE THREAD

**Issue by esbol-moldrakhmetov** [thecodingmachine/gotenberg#101]
Hi. I am in charge of using your library, it is beautiful. But there is one problem with the error \"message\":\"unoconv: exit status 6\", but after the command fc-cache -f -v everything works fine. How am I supposed to automate this so that I don't go into the pod every time?

**Comment by gulien** [comment]
Hello @esbol-moldrakhmetov 

Do you have more details about what's going on?

**Comment by esbol-moldrakhmetov** [comment]
Thanks, @gulien! I had a problem with the conversion, the problem was with the fonts. Is there a universal solution for fonts? Just my pptx files are not converted and return an error, I checked this problem is related to fonts.

**Comment by gulien** [comment]
Ok thank you for the details!

As a workaround, maybe you may create a cron job in the same pod for running this command.

**Comment by gulien** [comment]
@esbol-moldrakhmetov please reopen if you still have this issue with the newer version of Gotenberg.
