### ISSUE TITLE
Large quantity of zombie childs

### ISSUE THREAD

**Issue by babs** [thecodingmachine/gotenberg#103]
## Expected Behavior

No zombies :)

## Current Behavior
After some rendering, there is a non negligible amount of zombie childs on the server.
This might be also source of resource locking as process are not properly wiped from the system

## Possible Solution

"Wait" process once done and read the exit code.

https://stackoverflow.com/questions/36050503/golang-child-processes-become-zombies

**Comment by gulien** [comment]
Hello @babs 

For Google Chrome conversions (HTML, URL, Markdown), no golang command are run using `os/exec` package.

This package is used for Office and merge, but I'm using `Output()` method which calls `Wait()` internally.

Do you have more details?

**Comment by babs** [comment]
The weird thing is we don't use it for office rendering, that said, it's not disabled at startup.
I'll try, to start it disabling the soffice part via env.
That doesn't explain the two node process in defunct :/
Maybe those used to start pm2 (like pm2 start or resurrect) ?

![image](https://user-images.githubusercontent.com/117580/63266246-d586bd80-c28f-11e9-9312-e8d78173a2c9.png)

**Comment by gulien** [comment]
Thanks for the details!

Ok so PM2 processes are using `Start()` method which does not wait. Maybe I should call the `Wait()` method in a go routine.

**Comment by babs** [comment]
I also tried to use a dumb init to workaround the issue, without luck, I think you're right.
