### ISSUE TITLE
Update to LibreOffice 6.3 to improve document conversion fidelity

### ISSUE THREAD

**Issue by tiago-soczek** [thecodingmachine/gotenberg#107]
## Expected Behavior
Some documents (with floating images) are correctly converted to pdf.

## Current Behavior
Some documents (with floating images) are **NOT** correctly converted to pdf.

## Possible Solution
Migrate to libreoffice 6.3 solved this problem.

## Context
I've done a migration in my fork using buster-backports.

https://github.com/tiago-soczek/gotenberg/commit/b7dff92050666a41273fc6c516817e8888e8f137

I don't have much expertise with linux, so I don't know if this is the best way.

**Comment by gulien** [comment]
Hello @tiago-soczek 

Thank you for the details. I’ll check it out!
