### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by djlawler** [thecodingmachine/gotenberg#11]
Not a issue really.  I followed your instructions and scaled up gotenberg to 5 and then 10 containers (on Windows Hyper-V).  Calling the service from a java application resulted in the exact same performance (one document converted to pdf every 1 second).  This is a good result, but I'm confused as to why the performance stays (exactly!) the same.  I'm using Pentaho kettle, java and apache's HttpClient to make the Http posts.  I don't expect you to solve my problem...but any ideas on how to gain some insight on this would be appreciated!

**Comment by gulien** [comment]
Hello @djlawler 

I guess you don't send a lot of document to converts, so some Gotenberg instances are idle.

You may see the load balancing in action by running `docker-compose logs service_name`, where `service_name` is your Gotenberg service name.

If you send many documents to convert, it should not be the same Gotenberg container which handles the conversion.

**Comment by djlawler** [comment]
Thanks, yes I think the issue might be on the sending side...will try a few experiments!

**Comment by djlawler** [comment]
Just a follow up.  I was completely using docker-compose incorrectly.  I'm not smart enough to figure out how to add a real load balancer, so my solution for now is to use a docker-compose.yml with say 10 copies of the image, each running on a port like this:

version: '3'

services:

  # your others services
      
  gotenberg0:
    image: thecodingmachine/gotenberg:2.0.0
    ports:
      - "7000:3000

  gotenberg1:
    image: thecodingmachine/gotenberg:2.0.0
    ports:
      - "7001:3000
...etc...

then docker-compose up -d spins up the 10 (or whatever you want number of containers)...

Then the calling software has to be smart enough to do a 'round-robin' on the port #.  This gave me the performance boost that I was hoping for.

Then I use my calling software round-robin the ports and I got the

**Comment by gulien** [comment]
Thank you for the feedback!

It's weird, normally `docker-compose up --scale gotenberg=10` should work, as Docker automatically dispatches requests to a gotenberg service using the round robin strategy 🤔

Good to know: in order to work correctly, your application should also be in your `docker-compose.yml` file in order to communicate with your gotenberg services using the Docker network.
