### ISSUE TITLE
Parallel conversions with office

### ISSUE THREAD

**Issue by L3o-pold** [thecodingmachine/gotenberg#111]
From the README.MD the issue came from the unoconv library.
A workaround seems possible from https://github.com/unoconv/unoconv/issues/225#issuecomment-514236053

Is it possible to integrate this fix or keep an eye on a possible PR from it?

**Comment by gulien** [comment]
Hello @L3o-pold 

I'm working on this for the v6 actually 😄:

```go
return []string{
	// see https://ask.libreoffice.org/en/question/42975/how-can-i-run-multiple-instances-of-sofficebin-at-a-time/.
	fmt.Sprintf("-env:UserInstallation=file:///tmp/%d", p.port),
	"--headless",
	"--invisible",
	"--nocrashreport",
	"--nodefault",
	"--nofirststartwizard",
	"--nologo",
	"--norestore",
	fmt.Sprintf("--accept=socket,host=%s,port=%d,tcpNoDelay=1;urp;StarOffice.ComponentContext", p.host, p.port),
}
```

**Comment by L3o-pold** [comment]
Hi @gulien 

Oh ok, I saw your changelog but I was not sure that'll fix this issue.
Is that already available on the v6 branch?

**Comment by gulien** [comment]
It was not planned but I've encountered a memory issue with LibreOffice during load testing which forces me to rethink the process management almost entirely.

In others words, the goal is now to allow multiple instances of Google Chrome and Soffice to run in parallele, each one being able to do one conversion at a time. When a conversion is done, it checks the process memory usage and restart it if its higher than a configurable value. Having multiple instances helps mitigating those restart impact.

**Comment by L3o-pold** [comment]
Ok great, I'll keep an eye on the 6.0 release.
