### ISSUE TITLE
pageNumber , totalPages are not evaluated in the body

### ISSUE THREAD

**Issue by LoicHa** [thecodingmachine/gotenberg#112]
## Expected Behavior
Get the total amount of page or the page number in the body of the PDF

## Current Behavior
Nothing is displayed in the body ,working only in the footer and the header

## Steps to Reproduce (for bugs)
I created a repo, branch issue.
 https://github.com/LoicHa/docker-php-nginx-gotenberg/tree/issue
File is in www/conv.php

## Your Environment
Gotenberg 5
nginx:stable-alpine
php:fpm-alpine

**Comment by gulien** [comment]
Hello @LoicHa 

Indeed, this is done by Google Chrome directly and its scope is only the header/footer.
