### ISSUE TITLE
Verbose on gotenberg

### ISSUE THREAD

**Issue by eamanu** [thecodingmachine/gotenberg#113]
Hello,

Sorry if this is not the correct channel to publish this. I wan't to know if exist an
verbose option or at least the possibility that Gotenberg write on stdout
when is working.

I am trying to convert several docs/docxs but for some reason, that I can't detect yet,
gotenberg does not respond anymore the https requests.

**Comment by gulien** [comment]
Hello @eamanu 

This is done in #95 not yet ready though

Did you try to restart the instance of Gotenberg?

**Comment by eamanu** [comment]
Hi @gulien 

Yes we restart Gotenberg instance.  But if #106 solve that problem we can wait for it.

Close this issues because is done in #106
Thanks
