### ISSUE TITLE
Request time out when using Google Fonts in footer

### ISSUE THREAD

**Issue by pdoreau** [thecodingmachine/gotenberg#118]
## Expected Behavior
Google Fonts usable in footer. It works well in the main html.

## Current Behavior
Request time out logged form gotenberg 

## Steps to Reproduce

1. Write an html footer
2. Include google Fonts in the head tag

`<link rel="stylesheet" type="text/css" `href="https://fonts.googleapis.com/css?family=Titillium+Web:300,400,600&display=swap">`

3. Generate a complete doc from Html (main html with footer)

## Logs (LOG_LEVEL="DEBUG")
`{"time":"2019-10-02T16:03:59.181326789Z","id":"","remote_ip":"...","host":"pdf-generator:3000","method":"POST","uri":"/convert/html","user_agent":"GuzzleHttp/6.3.3 curl/7.61.1 PHP/7.2.19","status":408,"error":"code=408, message=Request Timeout","latency":10004439015,"latency_human":"10.004439015s","bytes_in":18447,"bytes_out":30}`

## Your Environment

* Version used: 5
* Operating System and version: Ubuntu / docker-compose

**Comment by M-ZubairAhmed** [comment]
@admin should i take a look at this ?

**Comment by gulien** [comment]
@pdoreau could you try with version 6?

**Comment by pdoreau** [comment]
@gulien same kind of message with v6 , "context has timed out" :
```
{"level":"error","msg":"cdp.Page: PrintToPDF: context deadline exceeded","op":"xhttp.htmlHandler: xhttp.convertSync: xcontext.MustHandleError: printer.chromePrinter.Print","time":"2019-10-02T17:42:12Z","trace":"..."}
{"bytes_in":"17318","bytes_out":"36","host":"pdf-generator:3000","latency":"10009876198","latency_human":"10.009876198s","level":"error","method":"POST","msg":"request failed","op":"context.Context.LogRequestResult","path":"/convert/html","referer":"","remote_ip":"...","status":504,"time":"2019-10-02T17:42:12Z","trace":"...","uri":"/convert/html","user_agent":"GuzzleHttp/6.3.3 curl/7.61.1 PHP/7.2.19"}
```

**Comment by gulien** [comment]
@pdoreau it seems that there are some limitations for footer / header: https://github.com/GoogleChrome/puppeteer/issues/2916#issuecomment-406366027.

Note: Gotenberg  and puppeteer uses the same Google Chrome API.

**Comment by gulien** [comment]
I’ll update the documentation to highlight those limitations 👍

For now a workaround would be to install the fonts directly in the Docker image.

**Comment by M-ZubairAhmed** [comment]
@gulien can i update that info in doc?
