### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by jrios2006** [thecodingmachine/gotenberg#123]
Hello I have edit the docker-compose-yml. I think that the file needs specify ports.
My yml file is

`version: '3'

services:

  `#` your others services

  gotenberg:
    image: thecodingmachine/gotenberg:6
    ports:
      - 3000:3000`

If the ports is not defined I do not know how to call via http rest

**Comment by jrios2006** [comment]
For example if my file is to change the port to access:

`version: '3'
services:
  # your others services
  gotenberg:
    image: thecodingmachine/gotenberg:6
    ports:
      - 4000:3000`


> If I execute

 `docker-compose up -d` 

> to run the container and I execute

`docker-compose ps` 

> I have 

`        Name                 Command         State           Ports         
---------------------------------------------------------------------------
gotenberg_gotenberg_1   /tini -- gotenberg   Up      0.0.0.0:4000->3000/tcp`

> The I can execute

`curl --request POST --url http://localhost:4000/convert/url --header 'Content-Type: multipart/form-data' --form remoteURL=https://google.com --form marginTop=0 --form marginBottom=0 --form marginLeft=0 --form marginRight=0 -o resultjttp.pdf`

> and the result is

`--form marginBottom=0 --form marginLeft=0 --form marginRight=0 -o resultjttp.pdf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76358  100 75794  100   564  55404    412  0:00:01  0:00:01 --:--:-- 55776`

> but I can not change the port 3000 in docker-comppose.yml file

**Comment by LoicHa** [comment]
You need to add environment config aswell
```
    environment:
      DEFAULT_LISTEN_PORT: '4000'
```

**Comment by jrios2006** [comment]
Thanks

**Comment by jrios2006** [comment]
My docker-compose.yml is
`version: '3'

services:

  `#` your others services

  gotenberg:
    image: thecodingmachine/gotenberg:6
    environment:
      DEFAULT_LISTEN_PORT: '4000'
    ports:
      - 4000:4000`
