### ISSUE TITLE
Cookies html and convert pdf

### ISSUE THREAD

**Issue by jrios2006** [thecodingmachine/gotenberg#126]
Hello I have convert a web site, by example **[https://aprendiendoavirtualizar.com/mobaxterm-exportar-e-importar-todas-las-sesiones-a-un-fichero/](https://aprendiendoavirtualizar.com/mobaxterm-exportar-e-importar-todas-las-sesiones-a-un-fichero/)** with this command
`curl --request POST --url http://localhost:4000/convert/url --header 'Content-Type: multipart/form-data' --form remoteURL=https://aprendiendoavirtualizar.com/mobaxterm-exportar-e-importar-todas-las-sesiones-a-un-fichero/ -o resultkk.pdf`

When I open with pdf viewer I have this text in all pages

> Privacidad y cookies: est e sitio utiliza cookies. Al continuar utilizando este sitio web,
aceptas su uso.
Para obtener más información, incluido cómo controlar las cookies, consulta aquí:
Política de cookie
VMCE V9
Cerrar y aceptar

Do you know if its its possible that chrome accepts this message to get a clean pdf without a cookie message with any environment variable?
![Captura de pantalla de 2019-10-08 20-56-57](https://user-images.githubusercontent.com/33350002/66424613-3c159580-ea0e-11e9-9ffc-e402e2f511d8.png)

Best regards,

Julio.

**Comment by gulien** [comment]
Hello @jrios2006 

It would be complicated: this cookie panel is implemented is various way across websites.

**Comment by jrios2006** [comment]
Hello may be a possible solution is install a chrome extension to accept cookies.

Do you think that it is possible install [https://chrome.google.com/webstore/detail/i-dont-care-about-cookies/fihnjjcciajhdojfnbdddfaoknhalnja](https://chrome.google.com/webstore/detail/i-dont-care-about-cookies/fihnjjcciajhdojfnbdddfaoknhalnja) in the container?

I can see this video in [https://www.youtube.com/watch?v=ocdHgPVAm1M](https://www.youtube.com/watch?v=ocdHgPVAm1M)

Best regards, 

Julio.
