### ISSUE TITLE
Access to the local documentation

### ISSUE THREAD

**Issue by jrios2006** [thecodingmachine/gotenberg#127]
Hello in Quick Start Section says em that 
the API is available in [http://localhost:3000](http://localhost:3000)

When my docker image is up my http://localhost:4000 says me 

> "an internal error has occurred: please contact technical support"
I have run a image with a docker-compose file. So you know that I write in compose file anything to view the API?.

Best regards

![Captura de pantalla de 2019-10-08 22-39-39](https://user-images.githubusercontent.com/33350002/66431985-602ca300-ea1d-11e9-9338-c04d104e8f39.png)

**Comment by gulien** [comment]
Hello @jrios2006

Show me your `docker-compose.yml` file :)

**Comment by jrios2006** [comment]
[gotemberg.zip](https://github.com/thecodingmachine/gotenberg/files/3708107/gotemberg.zip)
This is my docker compose file with 6001 port.
