### ISSUE TITLE
Japanese characters are not supported

### ISSUE THREAD

**Issue by dav009** [thecodingmachine/gotenberg#13]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Expected Behavior
Japanese characters are shown

## Current Behavior
Japanese characters appear as squares

## Possible Solution
previous solution pointed out on "updating dockerfile" any specific hints? .
I tried setting:
```
ENV LC_ALL=ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP.UTF-8
```
in the container but it did not work 🤔

**Comment by dav009** [comment]
done, installing fonts in the container did the trick:
```
RUN apt-get install -Vy ttf-wqy-zenhei fonts-arphic-ukai fonts-arphic-uming
```

**Comment by ssaunier** [comment]
It seems that Gotenberg is now packaged with _lots_ of fonts, if you like me stumbled upon this issue on a Google Search, have a look at:

https://github.com/gotenberg/gotenberg/blob/main/build/Dockerfile#L68
