### ISSUE TITLE
Request to reference html, header/footer and css documents with raw html text variable - go client

### ISSUE THREAD

**Issue by spdrcd** [thecodingmachine/gotenberg#131]
I'm looking to use the client to call this service. I am wondering if there is anyways to pass the html and css file using raw text? Instead of referencing the actual local file names?

**Comment by gulien** [comment]
Hello @spdrcd 

Make sense. Currently neither the PHP or Go client have a native method to do this.

Feel free to open a PR 👍😁

**Comment by spdrcd** [comment]
is there an example of how to do this using curl request?

**Comment by gulien** [comment]
IMO it is more related to the PHP and Go clients. Could you open an issue in both of them? Thank you 👍

**Comment by spdrcd** [comment]
@gulien duplicate issue post created at #134

**Comment by spdrcd** [comment]
@gulien Currently I have a way to do it. From Html String to call gotenberg using the go client. It basically  uses golang's ""io/ioutil" WriteFile() function to write files then deletes after. 
Is there anyways to avoid passing in only fileName string and just passes the entire html string along as some kind of string or byte[] data?

**Comment by spdrcd** [comment]
@gulien Yes, I am also planning to make a PR onto to the go-client this week.
