### ISSUE TITLE
header and footer element using style such as background-color and color

### ISSUE THREAD

**Issue by spdrcd** [thecodingmachine/gotenberg#132]
#124  Expected Behavior
header and footer element using style such as background-color and color should work properly

## Current Behavior
background-color that is set for class on header or footer's .html file
With example below 
```
<style>
.someClass {
background-color: #000000;
font-color: #ffffff;
}
</style>
...
...
<span class="someClass">stuff</span>"
```
then

---> generate file ---->

The generated header and footer part of the pdf file does not show the set background fill color.
and the font color, which is suppose to show as white (#ffffff) appears as grey.

## Your Environment
* Version used: using golang client gotenberg-go-client-6.0.1
* Operating System and version: windows version 10.0.17134 -- running using golang client

**Comment by twgraham** [comment]
I've experienced this too. I think this is an [issue](https://github.com/GoogleChrome/puppeteer/issues/2182) (feature?) with the way Google Chrome renders PDF's by default.

The fix should be adding a css property `-webkit-print-color-adjust: exact`. Others have suggested that it can be changed by using a property `printBackground: true` in puppeteer, though I don't know if Gotenberg forwards that property?

**Comment by gulien** [comment]
The property printBackground is set to true in Gotenberg 👍

**Comment by spdrcd** [comment]
The solution with ```-webkit-print-color-adjust: exact;```
on all the inherit class seems to work well. colors such as background color and text colors are working now.

**Comment by gulien** [comment]
I'll update the documentation. Thank you @twgraham

**Comment by Treize2** [comment]
@gulien it seems that the css colors needs to be set as !important also.
