### ISSUE TITLE
V 6.x Merge Order Issue w/ 4 or more pdfs

### ISSUE THREAD

**Issue by chrismo111** [thecodingmachine/gotenberg#139]
When merging 4 or more files named a.pdf ,b.pdf ,c.pdf ,d.pdf the merge result file puts them out of order.  In my tests when you have 2 or 3 files the merge is always done in the proper order. Not so with 4 or more.

We've been successfully merging 20+ pdfs using version 5.x for several months.

## Expected Behavior
Merges should be done alphabetically by file name as described in the documentation.

## Current Behavior
With 3 or more pdfs name named a.pdf ,b.pdf ,c.pdf ,d.pdf the merge result has the content in random order.  The merge result order can be different each time a test is run.

## Steps to Reproduce (for bugs)
 Run
<pre>
 curl --request POST \
    --url http://localhost:3000/merge \
    --header 'Content-Type: multipart/form-data' \
    --form files=@A.pdf \
    --form files=@B.pdf \
    --form files=@C.pdf \
    --form files=@D.pdf \
    --form files=@E.pdf \
    --form files=@F.pdf \
    --form files=@G.pdf \
    -o result.pdf
 </pre>
## Docker run command
docker run --name gotenbee_V603 -e DEFAULT_GOOGLE_CHROME_RPCC_BUFFER_SIZE=104857600 -e DEFAULT_WAIT_TIMEOUT=1800 -e DISABLE_UNOCON=1 -e MAXIMUM_WAIT_TIMEOUT=1800 -e LOG_LEVL=DEBUG -p:3000:3000 "thecodingmachine/gotenberg:latest"

## Logs (LOG_LEVEL="DEBUG")
Log entries for 3 attempts with 7 files named a.pdf through g.pdf are below
```json
{"level":"info","msg":"Gotenberg 6.0.3","op":"main","time":"2019-11-01T15:16:46Z","trace":"system"}
{"level":"info","msg":"http server started on port '3000'","op":"main","time":"2019-11-01T15:16:47Z","trace":"system"}
{"bytes_in":"150606","bytes_out":"147756","host":"localhost:3000","latency":"313460800","latency_human":"313.4608ms","level":"info","method":"POST","msg":"request handled","op":"context.Context.LogRequestResult","path":"/merge","referer":"","remote_ip":"172.17.0.1","status":200,"time":"2019-11-01T15:17:12Z","trace":"lowH6gDJUHTMZgWgw0vCezymepaJ3Iey","uri":"/merge","user_agent":"curl/7.55.1"}
{"bytes_in":"150606","bytes_out":"147756","host":"localhost:3000","latency":"261428400","latency_human":"261.4284ms","level":"info","method":"POST","msg":"request handled","op":"context.Context.LogRequestResult","path":"/merge","referer":"","remote_ip":"172.17.0.1","status":200,"time":"2019-11-01T15:18:08Z","trace":"9ADcVKN7QUGFVD4oY0ATx7g86F74V2Kc","uri":"/merge","user_agent":"curl/7.55.1"}
{"bytes_in":"150606","bytes_out":"147756","host":"localhost:3000","latency":"277160400","latency_human":"277.1604ms","level":"info","method":"POST","msg":"request handled","op":"context.Context.LogRequestResult","path":"/merge","referer":"","remote_ip":"172.17.0.1","status":200,"time":"2019-11-01T15:18:36Z","trace":"07UYP0UJAZLXOaPoI0O9ufkcTtUPzqnp","uri":"/merge","user_agent":"curl/7.55.1"}
```
## Environment
* Gotenberg version used :  6.0.3  -- all prior 6.x versions have the same issue
* Operating System and version:  Windows 10 Enterprise.
* Docker info:  Running the image in a linux container via  Docker version 19.03.4, build 9013bf5
* Curl: curl/7.55.1

**Comment by gulien** [comment]
Hello @chrismo111! Version `6.0.4` should fixe your issue 👍
