### ISSUE TITLE
Conversion Office Documents

### ISSUE THREAD

**Issue by dion96** [thecodingmachine/gotenberg#140]
Most office documents like Word, Excel and Powerpoint can be converted but some documents have some problems. A 500 error is returned with the message unoconv with exit status 5.

**Comment by gulien** [comment]
Hello @dion96 

Which version of Gotenberg? Could you provide some logs?

**Comment by dion96** [comment]
gotenberg version 5 with the use of docker

**Comment by gulien** [comment]
Please try with version 6 first 😃

**Comment by dion96** [comment]
Oh there is an update! Thanks I wil try that :)

**Comment by gulien** [comment]
@dion96 feel free to reopen this issue if the latest version fixes your problem 👍
