### ISSUE TITLE
change the client for converting html to PDF 

### ISSUE THREAD

**Issue by rimoi** [thecodingmachine/gotenberg#142]
There is a way to change the client for converting `HTML` to `PDF` from `chrome` to `firefox`? 

Thanks.

**Comment by gulien** [comment]
Hello @rimoi 

Not currently and probably never to be honest 😬 

Why would you want to use Firefox instead of Chrome?

**Comment by rimoi** [comment]
Hello gulien,
Chrome does not handle hyphenation in texts it does not support property css hyphens!

**Comment by gulien** [comment]
Ok! Currently Gotenberg is highly dependent on Chrome, and I'm not sure it will switch to Firefox in a near future 😄 closing for now
