### ISSUE TITLE
Error context has timed out

### ISSUE THREAD

**Issue by rimoi** [thecodingmachine/gotenberg#144]
When I want to generate a `Zip` (30 `pdf`'s one after the another) **Api Gotenberg** gives me an error

**Error :** 
` PHP Fatal error:  Uncaught TheCodingMachine\\Gotenberg\\ClientException: {"message":"context has timed out"}`

**my code to generate one pdf :** 
```
// ...

$pathFileNamePdf = $this->tmpPath.$this->fileNamePdf;
$client = new Client($this->linkGotenberg, new \Http\Adapter\Guzzle6\Client());
$index = DocumentFactory::makeFromString('index.html', $this->content); 
$request = new HTMLRequest($index);
$request->setPaperHeight(50);
$res = $client->store($request, $this->tmpPath.$this->fileNamePdf);

// create Zip
exec('cd  '. $this->tmpPath .'; zip -r ' . $this->zipDirName . '.zip ');
```
Thanks

**Comment by gulien** [comment]
Hello @rimoi 

You should increase the `waitTimeout`. See https://thecodingmachine.github.io/gotenberg/#timeout

**Comment by rimoi** [comment]
Hello @gulien,

I increased the `waiting time` (to `5`) and that of the `Guzzle` client but the problem is still there!

**Comment by gulien** [comment]
By default the `waitTimeout` is `10`! More details here https://thecodingmachine.github.io/gotenberg/#environment_variables.default_wait_timeout 👍

**Comment by rimoi** [comment]
I test with `waitTimeout = 30` it seems to work !

**Question :** How is the concurency management in Gotenberg? we have a call limit?

**Comment by gulien** [comment]
😄 https://thecodingmachine.github.io/gotenberg/#scalability

**Comment by cristiangq** [comment]
Hi, 
I test with waitTimeout = 30, but not working. Give the same error. `{"message":"context has timed out"}`
