### ISSUE TITLE
Basic authentication vulnerable to timing attacks

### ISSUE THREAD

**Issue by bgentry** [thecodingmachine/gotenberg#147]
Hi there! I [commented](https://github.com/thecodingmachine/gotenberg/pull/128#discussion_r345591578) on the PR that added basic auth (#128) but also wanted to open an issue here to make sure it was noticed.

@odarriba @gulien at a glance it appears that this HTTP Basic Auth implementation is vulnerable to timing attacks because it uses plain `==` to compare credentials rather than using a secure constant time comparison operation.

You can see one example of how to do this with a reasonable level of security in https://github.com/goji/httpauth/pull/2: they sha256 all of the values, and then use `subtle.ConstantTimeCompare` on the resulting slices.

**Comment by odarriba** [comment]
Totally agree on this.

#128 appears as merged, but it was rolled back, so there is no real risk at the moment. 

When someone take this feature again (if needed, which is the main reason to rolled it back) they should look at this implementation. Thanks for the information! <3
