### ISSUE TITLE
creating new browser context: cdp.Target: CreateBrowserContext: rpc er ror: Not allowed. (code = -32000)

### ISSUE THREAD

**Issue by HuaShuoYa** [thecodingmachine/gotenberg#15]
![tim 20181122165436](https://user-images.githubusercontent.com/18712863/48891804-58045d00-ee77-11e8-9d84-1f7062cc1049.png)
![tim 20181122165529](https://user-images.githubusercontent.com/18712863/48891838-6e121d80-ee77-11e8-95bd-674c7f269c93.png)
source file 
[temp.txt](https://github.com/thecodingmachine/gotenberg/files/2607259/temp.txt)
docker container ping image host is success

**Comment by gulien** [comment]
Hello,

I guess it's because some fonts are missing: you should extend the Gotenberg image by adding those fonts.

**Comment by gulien** [comment]
You may try it again with the new version of Gotenberg: it should work. Don’t forget to send those images in your request! See https://thecodingmachine.github.io/gotenberg/#html.assets

**Comment by gulien** [comment]
The browser is already installed in the image.
This issue is about creating a new RPC connection to the Chrome Debugging Protocol target, and I got the same issue in Travis CI 🤔 

I need to investigate this.

**Comment by gulien** [comment]
Could you provide more details about where do you launch Gotenberg (local remote)? What's your operating system?

**Comment by HuaShuoYa** [comment]
> Could you provide more details about where do you launch Gotenberg (local remote)? What's your operating system?

local server(Local Area Network)
CentOS Linux release 7.2.1511 (Core)  
x86_64
docker common:"docker run -d --rm -p 3000:3000 thecodingmachine/gotenberg:3"
Still need more information?

**Comment by HuaShuoYa** [comment]
cool!But I recommend using A4 paper by default. If I don't pass the parameters "paperWidth", "paperHeight", some content will be incomplete.(with google translate !Haha!)
![a6_pdf](https://user-images.githubusercontent.com/18712863/49912425-19d1ea80-fec5-11e8-9940-b98282957a71.png)
![default_pdf](https://user-images.githubusercontent.com/18712863/49912429-1c344480-fec5-11e8-900a-d6d5bbb80a7b.png)

**Comment by gulien** [comment]
A4 is actually the default format :) if you want, you may reduce the margins instead of changing the paper size :)

Feel free to reopen this issue if needed :)
