### ISSUE TITLE
Feature Request: Specify Output Format

### ISSUE THREAD

**Issue by ocomsoft** [thecodingmachine/gotenberg#150]
It would be awesome if we could specify the output format ie not just PDF but any office format uniconv supports a number of formats http://dag.wiee.rs/home-made/unoconv/

For example this could be used to extract the text from a HTML or DOCX or even a PDF. 

Still an awesome project

**Comment by gulien** [comment]
Hello @ocomsoft 

Gotenberg is focused only on converting various sources to PDF :)
