### ISSUE TITLE
Support for CSS Paged Media Module Level 3

### ISSUE THREAD

**Issue by MaurizioMoreo** [thecodingmachine/gotenberg#151]
It seems to fail with [some painting rules](https://www.w3.org/TR/css-page-3/#painting) as **@bottom-center**:

`
@page {
            @bottom-center {
                content: counter(page);
            }
        }
`

**Comment by gulien** [comment]
Hello @MaurizioMoreo 

It sounds more like a Google Chrome limitation on which Gotenberg relies.

**Comment by MaurizioMoreo** [comment]
Thank you @gulien, I'm comparing it with [Flying Saucer](https://github.com/flyingsaucerproject/flyingsaucer) that seems to support it, do you have any ideas on how to print page numbers with Gotenberg?

**Comment by gulien** [comment]
You may find information on that in the documentation (HTML/URL/Markdown only): https://thecodingmachine.github.io/gotenberg/#html.header_and_footer :)

**Comment by MaurizioMoreo** [comment]
Of course, I mean by some other supported css rule, thank you anyway :+1:
