### ISSUE TITLE
Allow http namespacing in the url 

### ISSUE THREAD

**Issue by ecasilla** [thecodingmachine/gotenberg#152]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Expected Behavior

I would like the ability to set the root url path for the service so that it doesn't pollute the / path on the load balancer. something like `https://domain.com/gotenberg/convert/html` would be helpful since I do service discovery via url paths.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by gulien** [comment]
Hello @ecasilla 

It should be quite easy to implement!

What kind of load balancer are you using?
Does the service discovery via URL path a common practice?

**Comment by ecasilla** [comment]
So for aws alb when using ECS you can say anything for api/v1/service_name_a goes to this cluster and for api/v1/service_name_b goes to this cluster
