### ISSUE TITLE
 print title does not take effect

### ISSUE THREAD

**Issue by yoyomule** [thecodingmachine/gotenberg#159]
#45  Expected Behavior

Hello, I set the print title in excel and set the top two lines as the title. But I found that when the output is pdf, this setting does not take effect. Can you consider adding this function?Thanks.

## Your Environment

* Version used:6.1.1
* Operating System and version:centos 7

**Comment by gulien** [comment]
It might be related with how LibreOffice handles the conversions. Did you try to convert your Excel file to PDF with LibreOffice directly?
