### ISSUE TITLE
Issue building 

### ISSUE THREAD

**Issue by DionDavid** [thecodingmachine/gotenberg#16]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Expected Behavior

Finishing all steps for building the image from the Dockerfile

## Current Behavior

Step 6/11 : COPY .ci/gotenberg /usr/bin/gotenberg
COPY failed: stat /var/lib/docker/tmp/docker-builder832472548/.ci/gotenberg: no such file or directory

## Context
I tried to run the following command in terminal:
docker build -t gotenberg .

## Your Environment
Mac OS X Mojave 10.14.1

**Comment by headz68** [comment]
@DionDavid I put [this](https://github.com/thecodingmachine/gotenberg/releases/download/v2.0.0/gotenberg_Linux_x86_64.tar.gz) binary from the [releases](https://github.com/thecodingmachine/gotenberg/releases) page into the .ci folder and the container builds successfully.

**Comment by gulien** [comment]
Hello guys!

I'm working on the v3 of Gotenberg (Chrome headless instead of wkhtmltopdf etc.) so sorry for the delay.

I confirm @headz68 solution works!

**Comment by gulien** [comment]
Closing this issue as it is no more revelant with the new version of Gotenberg.
