### ISSUE TITLE
Images in old DOC/XLS/PPT files are not displayed

### ISSUE THREAD

**Issue by ganzux** [thecodingmachine/gotenberg#160]
Using the latest version, I am trying to convert some old DOC/XLS/PPT files into PDF and everything works fine, but not the images (I have the same files in the new formats and the conversion is correct)

Having a look at the logs doesn't look like any error...

`{"level":"debug","msg":"resource directory 'b3gbxtfXim1pxGuAroJJKEu1G0n5enS0' created","op":"resource.New","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'resultFilename' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'waitTimeout' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'webhookURL' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'webhookURLTimeout' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'remoteURL' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'waitDelay' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'paperWidth' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'paperHeight' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'marginTop' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'marginBottom' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'marginLeft' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'marginRight' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'landscape' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"added 'googleChromeRpccBufferSize' with value '' to resource args","op":"resource.Resource.WithArg","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"resource file 'test.doc3169563329644977027.doc' created","op":"resource.Resource.WithFile","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"handling Office request...","op":"xhttp.officeHandler","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"no 'webhookURL' found, converting synchronously","op":"xhttp.convert","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"options: {WaitTimeout:10 Landscape:false}","op":"printer.logOptions","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"creating context with '10.00s' of timeout...","op":"xcontext.WithTimeout","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"converting '/gotenberg/tmp/b3gbxtfXim1pxGuAroJJKEu1G0n5enS0/test.doc3169563329644977027.doc' to PDF...","op":"printer.officePrinter.Print","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"executing command: unoconv --user-profile ///tmp/36629 --port 36629 --format pdf --output /gotenberg/tmp/b3gbxtfXim1pxGuAroJJKEu1G0n5enS0/0jjjGgkiLWYn9DuN7HqzKkICvrWGfOkfz.pdf /gotenberg/tmp/b3gbxtfXim1pxGuAroJJKEu1G0n5enS0/test.doc3169563329644977027.doc","op":"xexec.LogBeforeExecute","time":"2019-12-19T11:57:21Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"command 'unoconv --user-profile ///tmp/36629 --port 36629 --format pdf --output /gotenberg/tmp/b3gbxtfXim1pxGuAroJJKEu1G0n5enS0/0jjjGgkiLWYn9DuN7HqzKkICvrWGfOkfz.pdf /gotenberg/tmp/b3gbxtfXim1pxGuAroJJKEu1G0n5enS0/test.doc3169563329644977027.doc' finished","op":"xexec.Run","time":"2019-12-19T11:57:22Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"'jjjGgkiLWYn9DuN7HqzKkICvrWGfOkfz.pdf' created","op":"printer.officePrinter.Print","time":"2019-12-19T11:57:22Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"only one PDF created, nothing to merge","op":"printer.officePrinter.Print","time":"2019-12-19T11:57:22Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"no 'remoteURL' found, using generated filename 'vEQyj6mHiR40Xm3a9iJUR4E8YN0RwZTX.pdf'","op":"xhttp.convertSync","time":"2019-12-19T11:57:22Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"level":"debug","msg":"resource directory '/gotenberg/tmp/b3gbxtfXim1pxGuAroJJKEu1G0n5enS0' removed","op":"resource.Resource.Close","time":"2019-12-19T11:57:22Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0"}
{"bytes_in":"2653921","bytes_out":"8384","host":"localhost:3000","latency":"1637832400","latency_human":"1.6378324s","level":"info","method":"POST","msg":"request handled","op":"context.Context.LogRequestResult","path":"/convert/office","referer":"","remote_ip":"172.17.0.1","status":200,"time":"2019-12-19T11:57:22Z","trace":"b3gbxtfXim1pxGuAroJJKEu1G0n5enS0","uri":"/convert/office","user_agent":"Java/1.8.0_231"}`

`{"level":"info","msg":"Gotenberg 6.0.4","op":"main","time":"2019-12-19T12:10:44Z","trace":"system"}
{"level":"debug","msg":"configuration: {maximumWaitTimeout:30 maximumWaitDelay:10 maximumWebhookURLTimeout:30 defaultWaitTimeout:10 defaultWebhookURLTimeout:10 defaultListenPort:3000 disableGoogleChrome:false disableUnoconv:false logLevel:DEBUG maximumGoogleChromeRpccBufferSize:104857600 defaultGoogleChromeRpccBufferSize:1048576}","op":"main","time":"2019-12-19T12:10:44Z","trace":"system"}
{"level":"debug","msg":"starting new Google Chrome headless process on port 9222...","op":"chrome.Start","time":"2019-12-19T12:10:44Z","trace":"system"}
{"level":"debug","msg":"executing command: google-chrome-stable --no-sandbox --headless --font-render-hinting=medium --remote-debugging-port=9222 --disable-gpu --disable-translate --disable-extensions --disable-background-networking --safebrowsing-disable-auto-update --disable-sync --disable-default-apps --hide-scrollbars --metrics-recording-only --mute-audio --no-first-run","op":"xexec.LogBeforeExecute","time":"2019-12-19T12:10:44Z","trace":"system"}
{"level":"debug","msg":"waiting '500ms' for allowing Google Chrome to warmup","op":"chrome.warmup","time":"2019-12-19T12:10:44Z","trace":"system"}`

I included the converted file and a ZIP of the original one
[test.doc.zip](https://github.com/thecodingmachine/gotenberg/files/3983520/test.doc.zip)
[test.doc1576757500369.pdf](https://github.com/thecodingmachine/gotenberg/files/3983509/test.doc1576757500369.pdf)

Thanks,

**Comment by gulien** [comment]
Hello @ganzux 

It might be related to LibreOffice actually. Not sure I can do much.

**Comment by ganzux** [comment]
Thanks for the answer.

Is it any easy way to test that in LibreOffice?

Best regards,

*-----------------------------------Álvaro Alcedo Moreno*

**Comment by gulien** [comment]
Best option would be opening and saving those old files in a recent version of LibreOffice / Microsof office. Then retry the conversions with Gotenberg.

**Comment by ganzux** [comment]
Yeah, well, I am trying to automate the process. Do you have any tests with doc files with images?

Wondering if you can programmatically do it in your code; if the mime type of the file is an old Office one, convert it into the new format.

**Comment by gulien** [comment]
You may take a look at https://github.com/thecodingmachine/gotenberg/blob/master/test/testdata/office/document.docx for an example.

Not sure I can do it programmatically though.

**Comment by ganzux** [comment]
Well, I think you are not covering enough with those test files. 

Should you remove the support for DOC, PPT and XLS files from this library?

**Comment by gulien** [comment]
We're generating PDF from PPT in one of our project and it works just fine 🤔 
You should address you issue to the LibreOffice bug tracker directly.
