### ISSUE TITLE
Feature Request: Custom LibreOffice Version

### ISSUE THREAD

**Issue by hspak** [thecodingmachine/gotenberg#161]
How easy would it be to use a different version of LibreOffice? v6.3 breaks certain formatting for a handful of documents while v6.2 appears to be more reliable.

Taking a look at the Dockerfile didn't make this immediately obvious, so I'm here instead 😄

**Comment by gulien** [comment]
Hello @hspak 

Indeed, we're using LibreOffice 6.3 (see https://github.com/thecodingmachine/gotenberg/issues/107) :smile: I should update the documentation about that.

What kind of issues do you have with 6.3?

**Comment by hspak** [comment]
Some docx to pdf conversions have minor differences, but large enough to be a problem like numbering formats being slightly off.

**Comment by gulien** [comment]
I think having two versions of LibreOffice in the same image is not a good idea.

It could be possible to provide different images of Gotenberg, each one having its own LibreOffice versions. But that would require extra work and support 😄
