### ISSUE TITLE
Fonts in Markdown to PDF

### ISSUE THREAD

**Issue by franchb** [thecodingmachine/gotenberg#162]
Need to render PDF from Markdown. Any options for changing default font?

I tried to add `Fira Code` font to Docker image according to [docs](https://thecodingmachine.github.io/gotenberg/#fonts), but nothing happens.

**Comment by gulien** [comment]
Hello @franchb 

As for HTML conversion, you could use Google fonts or send your own font with your assers 👍

**Comment by franchb** [comment]
Got it. Thank you!
