### ISSUE TITLE
Context Time out

### ISSUE THREAD

**Issue by ilamparithi10** [thecodingmachine/gotenberg#165]
I'm running docker run --rm -p 3000:3000 -e MAXIMUM_WAIT_TIMEOUT="1000.0" -e MAXIMUM_WAIT_DELAY="1000.0" thecodingmachine/gotenberg:6 on my terminal. I send an API request through postman to convert the doc/docx to PDF.

## Expected Behavior
It shouldn't return ** context timed out**
## Current Behavior
It always returns ** context timed out**

## Logs (LOG_LEVEL="DEBUG")
{"level":"info","msg":"Gotenberg 6.1.2","op":"main","time":"2020-01-09T13:10:58Z","trace":"system"}
{"level":"info","msg":"http server started on port '3000'","op":"main","time":"2020-01-09T13:11:04Z","trace":"system"}
{"level":"error","msg":"context deadline exceeded","op":"xhttp.officeHandler: xhttp.convertSync: xcontext.MustHandleError: printer.officePrinter.Print: printer.unoconv: xexec.Run","time":"2020-01-09T13:11:17Z","trace":"ZIeVf5K0MhpcKJohXyqSzmBnf4UmexiZ"}
{"bytes_in":"16819663","bytes_out":"36","host":"localhost:3000","latency":"10317467517","latency_human":"10.317467517s","level":"error","method":"POST","msg":"request failed","op":"context.Context.LogRequestResult","path":"/convert/office","referer":"","remote_ip":"172.17.0.1","status":504,"time":"2020-01-09T13:11:17Z","trace":"ZIeVf5K0MhpcKJohXyqSzmBnf4UmexiZ","uri":"/convert/office","user_agent":"PostmanRuntime/7.20.1"}

## Your Environment

* Operating System and version: Ubuntu 18:04

**Comment by gulien** [comment]
You should also set the `DEFAULT_WAIT_TIMEOUT` or use the form field `waitTimeout`.

See https://thecodingmachine.github.io/gotenberg/#timeout.

**Comment by idenisovs** [comment]
For the 6th version of Gotenberg the proper link now is https://gotenberg.dev/docs/6.x/timeout
