### ISSUE TITLE
improve documentation to get this running on Google Cloud-Run

### ISSUE THREAD

**Issue by enigmae** [thecodingmachine/gotenberg#167]
After trying to get this container to work on google cloud run, there are issues where the conversions are not working.  

I have tested a CURL request upload an image to convert to PDF works locally on docker, also worked on Azure Container Instances, 

here is cloud-run issue
020-01-28T22:39:40Z{level: error, msg: context deadline exceeded, op: xhttp.officeHandler: xhttp.convertSync: xcontext.MustHandleError: printer.officePrinter.Print: printer.unoconv: xexec.Run, trace: 7a9DlMappjt4PGv0x0AdIuvQ6Ehq8WLO}

The setup was deploy container to google container registry, then setup cloud deployment, changed port to 3000, no security, and it uploads file but fails.

**Comment by gulien** [comment]
You should increase the wait timeout. See https://thecodingmachine.github.io/gotenberg/#timeout

**Comment by enigmae** [comment]
I tried and get same issue - i wonder cause i configured cloud-run on port 3000, but the way to send stuff in is port 80, I wonder if I should try to reconfigure the container to use port 80 or 443, or dynamically $port?  it might be getting data but can't return it cause of port mapping issues?

**Comment by enigmae** [comment]
01-31T18:13:25Z{bytes_in: 367267, bytes_out: 36, host: xyz.uc.a.run.app, latency: 8019833786, latency_human: 8.019833786s, level: error, method: POST, msg: request failed, op: context.Context.LogRequestResult, path: /convert/office, referer: , remote_ip: 2600:xxx
…
2020-01-31T18:13:25.529871ZPOST504321 B8 scurl/7.55.1 https://xyz.uc.a.run.app/convert/office

**Comment by enigmae** [comment]
{level: error, msg: context deadline exceeded, op: xhttp.officeHandler: xhttp.convertSync: xcontext.MustHandleError: printer.officePrinter.Print: printer.unoconv: xexec.Run, trace: zHrkJPDqlxa4P4skPsGRJUImSxfu0Lq8} this is the error

**Comment by enigmae** [comment]
I was able to get it working (on a differernt conversion) using /convert/url so i think ports are correct it has something to do with the office document conversion having issues.

**Comment by enigmae** [comment]
here is my test script - inside the converted data is an error, it says : {"message":"context has timed out"}

Here is my CURL i switched to using bash shell.  i have a simple doc file to convert to ppt, etc..
curl --request POST \
     --url https://XXX-iq2qd42bfq-uc.a.run.app/convert/office \
     --header 'Content-Type: multipart/form-data' \
     --form files=@result-test2.ppt \
     -o result-test3.doc \
     --form waitTimeout=10
 it waits 10 seconds then returns.

**Comment by enigmae** [comment]
the deployed image is basically the image for this code-repo no changes, and it works locally, and on Azure, but google cloud run is giving this issue.

**Comment by gulien** [comment]
Sorry for the delay ; you should increase the waitTime even more. Or try to increase the available memory on your CloudRun instance.

**Comment by enigmae** [comment]
Yes I had it set for up to 5 min, when i run this locally, or on Azure it returns in under 2 seconds, with my tests.  I suspect there is something wrong with how this deployment works in cloud-run, there might be some optimizations needed for google-cloudrun stability.

**Comment by ekeuus** [comment]
I tested it yesterday on cloud run and even though the startup is slow, it works perfectly.

**Comment by gulien** [comment]
Same I've tested it a few weeks back and it worked perfectly fine 🤔

**Comment by HectorBlisS** [comment]
Hey guys do you have a tutorial/blog post on how to config the image to run correctly in cloud run? I successfully deploy on cloud run but port 3000 doesn't seems to be receiving request, should I do something with the ports like switching to 80?

Thanks in advanced! awesome tool!
