### ISSUE TITLE
How to manage page break

### ISSUE THREAD

**Issue by jlgrau** [thecodingmachine/gotenberg#169]
## Expected Behavior
I would like to control the pdf page content with page break to be able to decide where the text should start (like in word)

## Current Behavior
Cannot control the page content when converting md or html to pdf

## Possible Solution
Create a special html tag 
<pagebreak></pagebreak>

**Comment by gulien** [comment]
Hello @jlgrau 
It could be possible via CSS.

**Comment by spdrcd** [comment]
is there anyways to control the margin after the page break?

**Comment by idenisovs** [comment]
@spdrcd Probably, CSS property [**page-break**](https://css-tricks.com/almanac/properties/p/page-break/) can help. Did you tried it?

**Comment by supermuesli** [comment]
CSS page-break doesn't do anything for me.

**Comment by braaar** [comment]
CSS `break-inside`, `break-after` and `break-before` work well for me. One thing I discovered that was not obvious at first was that flexboxes and grids don't work with `break-inside: 'auto'`, so in the print-facing stuff I was doing I have avoided using grids and flexboxes for the top level layouting. They simply don't play nicely with page breaking and try to enforce their own layout. I just let the content flow freely inside regular divs or use CSS `column-count` to make column layouts (can achieve some of the same things as grids)

@supermuesli

**Comment by supermuesli** [comment]
@braaar Exactly, I also re-layouted my template using simple divs after realising table rows (or really any element whose parent does not have `display: block`) don't synergize with page breaks.

**Comment by fatoon29** [comment]
Hello i have the same problem.
I create a template with `break-before: page;` in some div. 
If i press ctrl+p, it work,  but with gotenberg, it doesn't do anything.

**Comment by bvsn** [comment]
```CSS
```

**Comment by bvsn** [comment]
@fatoon29 

```css
.pagebreak {
    page-break-before: always;
    clear: both;
}
```

```html
<div>page 1</div>
```

Works for me.

**Comment by marcoshenke** [comment]
The best way I found was to place all the content within table structures, I didn't understand why page-break-before didn't work correctly for divs and other html elements, in my case it created an unwanted blank page.

`<table style=" border: none; width: 100%; border-collapse: collapse;">`
 `<tbody>` 
   `<tr>`
    `<td text-align: left; padding: 8px; border: none;>*rest of the html content here*</td>`
   `</tr>`
 `</tbody>`
`<table>`

CSS

`table {
      page-break-after:auto;
    }
    tr, td, div {
      page-break-inside:avoid;
      page-break-after:auto
    }`
