### ISSUE TITLE
Dockerfile with latest unoconv version

### ISSUE THREAD

**Issue by headz68** [thecodingmachine/gotenberg#17]
The unoconv version that installs from `apt-get` is `0.7` and the latest version is `0.8.2`. The output from `apt-cache search unoconv` is :
```
unoconv:
  Installed: 0.7-1.1
  Candidate: 0.7-1.1
  Version table:
 *** 0.7-1.1 500
        500 http://httpredir.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```
So I guess I would need to install manually  in order to get the latest version. I've already reached out to see if the latest version can be published https://github.com/dagwieers/unoconv/issues/482. If that is not possible, I was wondering if there is any way that this repo can support a Dockerfile that builds latest unoconv manually with all its dependencies.

**Comment by gulien** [comment]
Does the `-P` option works for all documents types?

**Comment by headz68** [comment]
@gulien the only documentation I found for it was in the actual script file [here](https://github.com/dagwieers/unoconv/blob/master/unoconv#L774) Its a valid option that doesn't specify file types.

**Comment by gulien** [comment]
Interesting! The v3 has just been released: Gotenberg now handles paper size and orientation for HTML and Markdown conversions. This option is a good candidate for doing it too for Office conversions.

I'll try to install `unoconv` manually in the base Dockerfile.

**Comment by gulien** [comment]
@headz68 Gotenberg 3.1 should provide what you need. Feel free to reopen this issue if not 👍

**Comment by headz68** [comment]
Thanks! I appreciate the work you've put into this service. It's really helped me out because the sensitive nature of our documents won't allow us to send anything to cloud conversion tools!

**Comment by gulien** [comment]
Glad to help 👍
