### ISSUE TITLE
[Feature Request]  TOC generation

### ISSUE THREAD

**Issue by tonyellow** [thecodingmachine/gotenberg#186]
This is a very nice tool and it could completely remove the need of using wkhtmltopdf  in my projects. What is missing is the option to generate a table of contents. It's probably a feature more people would need. Keep up the good work.

**Comment by gulien** [comment]
Hello @tonyellow 

Thanks for the kind words! 

IMO it should be done by the user, not Gotenberg. For instance you may generate a TOC with Word directly 😄
