### ISSUE TITLE
Can we have page number data to use for dynamically rendering blocks of HTML?

### ISSUE THREAD

**Issue by danielopatich** [thecodingmachine/gotenberg#195]
I see that there is a way to inject page number information in the header and footer by way of an html element/classname, but I'd like to have access to that info in the form of an integer.

Use case: I am using this library to generate PDF invoices for customers and I have a footer that I only need to show up on the last page. The line items that are displayed on the invoice are always changing thus there are endless combinations of an invoice so having that information is the only way for us to correctly format the invoice

**Comment by gulien** [comment]
Hello @danielopatich 

Gotenberg is "just" an API in front of Google Chrome, so this is unfortunately a limitation of the browser. There might be a workaround might with some JavaScript libraries though.
