### ISSUE TITLE
[Feature request] fill forms?

### ISSUE THREAD

**Issue by boxfoot** [thecodingmachine/gotenberg#198]
## Possible Solution
Would you consider adding a feature for form filling?  pdftk already supports this, so I expect it would be a relatively low-complexity addition.  Basically adding an endpoint e.g. /fillform which would accept a PDF and an FDF, run them through pdftk, and return the result.

(I may even give a go at a PR if you'd be open to considering it).

## Context
Looks like gotenberg already supports most of my PDF generation needs, but this is still outstanding.

**Comment by gulien** [comment]
Hello @boxfoot 

Currently I would like to stick Gotenberg to its initial goal (i.e convert files to PDF) 😄
Also, the less dependency we have on pdftk, the better; I would like to remove it in the future when we find a working Go solution for merging PDF.

**Comment by rodnaph** [comment]
Has anything changed with your position on this, I see Gotenberg now has features for flattening, rotating, read/write metadata, etc...  would you reconsider adding support for filling fields?
