### ISSUE TITLE
Critical vulnerability

### ISSUE THREAD

**Issue by br0xpl** [thecodingmachine/gotenberg#199]
Hi there, 
I have identified several vulnerabilities in Gotenberg which all lead to arbitrary code execution in the container. 

Following responsible disclosure model I would like to give contributors more details so that you could fix this. 

@gulien : please provide some e-mail and pgp key so that I can contact you securely. 

After fix I'm planning to make a disclosure on seclists. 

I have also requested CVE IDs for the issues.  

Best regards!

**Comment by gulien** [comment]
Hey @br0xpl 

All PGP information may be retrieved here: https://keys.openpgp.org/vks/v1/by-fingerprint/4EC89A8A6B947C8C68F9329350B105D91EA8B67B

**Comment by br0xpl** [comment]
Thanks! Will contact you as soon as possible (next few days cause I need to write it up together).

**Comment by gulien** [comment]
@br0xpl

**Comment by br0xpl** [comment]
@gulien : I've just sent you the details in an encrypted email. Please let me know if you got it and if it is readable.

Thanks!
