### ISSUE TITLE
Does it support generating fillable form inputs?

### ISSUE THREAD

**Issue by Kaos-Industries** [thecodingmachine/gotenberg#209]
I need to create many PDFs that require forms that can then be filled in Adobe Reader and saved, and am looking for the best tool to do so. Is Gotenberg currently capable of converting HTML form inputs into fillable PDF form inputs?

Thanks in advance.

**Comment by gulien** [comment]
Hey @Kaos-Industries 

That would have been great but currently Google Chrome (and therefore Gotenberg) does not handle that: https://stackoverflow.com/a/59648417/1425380.
