### ISSUE TITLE
installing the php client in Docker

### ISSUE THREAD

**Issue by richb201** [thecodingmachine/gotenberg#223]
I am trying to add in the php client. I have already added gotenburg to my docker-compose and it seems to come up OK.
 gotenberg:
    image: thecodingmachine/gotenberg:6
Now I am trying to install the php client. The instructs tell me to run:
$ composer require php-http/guzzle6-adapter
$ composer require thecodingmachine/gotenberg-php-client

I want to run these in my php-fpm container? When I open a /bin/bash cli and type "composer require php-http/guzzle6-adapter", the system seems to freeze. Is Composer already in the php-fpm container or should I be running these composer comands in the gotenberg:6 container?

**Comment by gulien** [comment]
Composer might not be available in your image. You should take a look at https://github.com/thecodingmachine/docker-images-php.

**Comment by richb201** [comment]
Julien, OK here is the issue. It is really an installation issue. I have
installed the Gotenberg Docker container via docker-compose using:
gotenberg:
    image: thecodingmachine/gotenberg:6
I think that I do have Composer installed, at least in my php-fpm
container.
I then try to run the example code: $client = new Client('
http://localhost:3000', new \Http\Adapter\Guzzle6\Client());
This fails with $Exception: message => 'Coding Machine Gotenberg/client'
not found.
So what I really need is installation help. If you want to call it a
project let call it "installation of Gotenberg". Give me an idea of price?
My PC is running Ubuntu and is available via TeamViewer or Skype.
Thanks, Rich

---------- Forwarded message ---------
