### ISSUE TITLE
Works only through Postman, Blank PDF through NodeJS POST

### ISSUE THREAD

**Issue by adame21** [thecodingmachine/gotenberg#237]
Hi,
So we set  up this app on our docker.
When I use /convert/html with Postman according to the documentation it works and I can save and view the HTML.
When I use Axios to post through NodeJS code I also get a response back but when i save it it shows up blank.
It seems the encoding of the HTML itself is faulty/wrong.
Heres the code generated by Postman I am using:
````javascript
var axios = require('axios');
var FormData = require('form-data');
var fs = require('fs');
var data = new FormData();
data.append('index.html', fs.createReadStream('C:/Users/adame/Desktop/tests/gotenberg/index.html'));

var config = {
    method: 'post',
    url: 'https://commons-gotenberg-mdpint.menora.co.il/convert/html',
    headers: {
        ...data.getHeaders(),
    },
    data: data
};

axios(config)
    .then(function (response) {
        fs.writeFileSync("./test.pdf", response.data)
    })
    .catch(function (error) {
        console.log(error);
    });
````

Heres a sample of the good PDF response: (just a sample of how the content inside the pdf objects look)
€4ת£‹–־iOZ0ע3‘¾xqe]¦זט¢1{‘V–´/—7¾¡iָףף»–._¡¦ׁףD׃´ע®‹חuMצ¹HCחָ'ˆ‰…iׂC—
ת|:=HֵFךאQLֿ¹Iץz.tפ¡qי’¥₪¨ת‹†ךY¾1•mקCzX@`Z׀ֱ8cd׃
₪oM*™(Dֲ…C%†Q0ֲױd–A@‹D+Yװד)1¬ְhT¿ַ<Gc)G1ְx‰6&
˜’(8ֹSh”תw²S2P‘˜J)@Nל[J£T`:9€.r3€P&¥³ָtS׀C™ְlֺRQ¹£ֹּ•˜Gך׳4†r€^

Heres a sample from the blank PDF response:
ן¿½|ן¿½:=Hן¿½Fן¿½ן¿½QLֿ¹Iן¿½z.tן¿½ן¿½qי’¥ן¿½ן¿½ן¿½ן¿½ן¿½ן¿½Yן¿½1ן¿½mן¿½CzX@ן¿½`Zן¿½ן¿½8cdן¿½
ן¿½oM*ן¿½(Dן¿½ן¿½C%ן¿½Q0ן¿½ן¿½ן¿½dן¿½A@ן¿½D+Yן¿½ן¿½)1ן¿½ן¿½ן¿½hן¿½Tן¿½ן¿½<Gc)G1ן¿½xן¿½6ן¿½&ן¿½
ן¿½ן¿½ן¿½ן¿½(8ן¿½ן¿½ן¿½Shן¿½ן¿½wן¿½S2Pן¿½ן¿½J)@��Nן¿½ן¿½[Jן¿½T`:9ן¿½.r3ן¿½ן¿½P&ן¿½ן¿½ן¿½tSן¿½Cן¿½ן¿½lן¿½Rן¿½Qן¿½ן¿½ן¿½ן¿½ּ•ן¿½Gן¿½ן¿½ן¿½4ן¿½rן¿½^
ּ§\`ן¿½_Q!ן¿½ן¿½X,ן¿½ן¿½ן¿½T,ן¿½"ן¿½?hן¿½ן¿½r*ן¿½ן¿½`ן¿½ן¿½J*Sן¿½$ן¿½VIן¿½ן¿½r`

What am I doing wrong here?

Thanks :)

**Comment by adame21** [comment]
Hi,
I'd like to update I found a way to get through this.
I simply used the gotenberg js client
This one: https://github.com/yumauri/gotenberg-js-client
Using this client made the PDF display properly.
I still dont know the root of the problem though...
Thanks ! :)

**Comment by novelnet** [comment]
Or use [js-file-download ](https://www.npmjs.com/package/js-file-download) with axios:

```
const formData = new FormData;
formData.append('files', doc, 'test.docx');

axios.post('http://localhost:3000/forms/libreoffice/convert', formData, {
        headers: { 'content-type': 'multipart/form-data' },
        responseType: 'blob'
    })
    .then(({ data }) => {
        FileDownload(data, `test.pdf`);
    });
```

**Comment by ThyDevourer** [comment]
Has anyone figured out how to solve this? I've been trying all day to generate a PDF from a node.js app through axios with no luck, this is the last thing I tried:
```
const html = Mustache.render(
  (await fs.readFile(options.templateDir)).toString(),
  { labels: data }
);

const css = (
  await fs.readFile('./utils/fonts/canaro.css')
).toString();

const form = new FormData();

form.append('index.html', Buffer.from(html), {
  filename: 'index.html',
  contentType: 'text/html',
});
form.append('canaro.css', Buffer.from(css), {
  filename: 'canaro.css',
  contentType: 'text/css',
});
form.append('paperWidth', '3');
form.append('paperHeight', '1');
form.append('landscape', 'false');
form.append('marginTop', '0.11811');
form.append('marginBottom', '0.11811');
form.append('marginLeft', '0.11811');
form.append('marginRight', '0.11811');

const res = await axios.post(
  'http://localhost:3001/forms/chromium/convert/html',
  form,
  { headers: form.getHeaders() }
);
```

**Comment by hajjoujti** [comment]
You need to add `responseType: 'arraybuffer'`.
I worked like that for me.
