### ISSUE TITLE
Please enable longer waitTimeout

### ISSUE THREAD

**Issue by adame21** [thecodingmachine/gotenberg#238]
Hi,
I have a request if possible.
Right now if I send a waitTimeout of >30 I get an error telling me it must be 30 or less.
Can the maximum waitTimeout be set to be possibly higher than 30 ?
Alternatively, can a higher timeout be configured through a .yaml file somewhere ?

Thanks ! :)

**Comment by gulien** [comment]
Hello @adame21!

Thank you for your interest :) you may find all information here: https://thecodingmachine.github.io/gotenberg/#timeout

**Comment by adame21** [comment]
Hi !
Thanks for the quick reply.
I looked there before opening this issue, thats why I even knew it was possible to pass this.
Unfortunately it does not say anything there about the limitation of 30sec.
If I try higher than 30 seconds, for example 31 seconds, I get status code 400 and this:
{
    "message": "'waitTimeout' should be < '30.000000', got '31.000000'"
}
Am I missing something right in front of me here? sorry if thats the case.
Thank you

**Comment by gulien** [comment]
Oh ok! Actually you should update the `MAXIMUM_WAIT_TIMEOUT` environment variable: https://thecodingmachine.github.io/gotenberg/#environment_variables.maximum_wait_timeout

**Comment by gulien** [comment]
I'll drop this mechanism in version 7 👍

**Comment by adame21** [comment]
Thank you so much!
Understood completely. 
Amazing project you have, keep up the good work!
:)
