### ISSUE TITLE
Internal error when merging PDF version 1.7

### ISSUE THREAD

**Issue by deedek** [thecodingmachine/gotenberg#247]
I get a message "an internal error has occurred: please contact technical support" when I try to merge PDF version 1.7

**Comment by gulien** [comment]
That's because PDFTk might not be able to merge PDFs for version > 1.7?
I plan to implement a solution for multiple "merger" in v7.

**Comment by gulien** [comment]
Hello @deedek 

Version 6.4 might resolve your issue 👍
