### ISSUE TITLE
Html to pdf conversion jumbles encoding

### ISSUE THREAD

**Issue by adame21** [thecodingmachine/gotenberg#254]
Hello,

So my source files are .mhtml  or .mht and I convert them to .html and add the proper meta tag.

These files contain hebrew

The result from the conversion returns gibberish like this:

````
לכבוד:
````
becomes
````
:􁓼􁓼􁓼􁓼􁓼
````

Is this some bad configuration? not supported? can any workaround be done?

Thanks :)

**Comment by gulien** [comment]
Hello @adame21 

Some fonts might be missing. 

See https://thecodingmachine.github.io/gotenberg/#fonts or https://github.com/thecodingmachine/gotenberg/blob/master/build/base/Dockerfile#L96 for ttf fonts.

**Comment by adame21** [comment]
Hi,
Thanks! understood.
Closing :)
