### ISSUE TITLE
How can i use for go build,don't use docker image?

### ISSUE THREAD

**Issue by lcp0578** [thecodingmachine/gotenberg#26]
How can i use for go build,don't use docker image?

**Comment by gulien** [comment]
Hello,

It could be possible but you'll need to:

1. Install Libreoffice with unoconv 0.8.2 
2. Install PM2
3. Install Google Chrome headless and update the binary name (https://github.com/thecodingmachine/gotenberg/blob/master/internal/pkg/pm2/chrome.go#L48)
4. `go build -o gotenberg -ldflags "-X main.version=${VERSION}" cmd/gotenberg/main.go`

**Comment by lcp0578** [comment]
Oh, thx
