### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by pedroalbanese** [thecodingmachine/gotenberg#264]
$ go build -ldflags=-s .
# github.com/thecodingmachine/gotenberg/internal/pkg/xexec
..\..\internal\pkg\xexec\xexec.go:69:11: undefined: syscall.Kill
..\..\internal\pkg\xexec\xexec.go:77:42: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr

How to proceed?

Thanks in advance.

**Comment by gulien** [comment]
Gotenberg has only been tested on an Ubuntu x86_64 Docker image. Did you tried to build an image using another base image?
