### ISSUE TITLE
Questions about configuring page layout and about using fonts

### ISSUE THREAD

**Issue by adame21** [thecodingmachine/gotenberg#265]
Hello :)
This is not a bug, more of a handling question.
I couldn't find an answer in the docs.
This is about HTML to PDF conversion.
1. Is it possible to somehow force the result pdf to be just 1 page? can I at all control how gotenberg will split the html ?
2. I couldn't understand well enough from the docs how to send a font, I messed around but couldn't use a font file and not a uri to the font. does it have to be a .woff file ? can .ttf be used ?
3. Is it possible to designate a background image somehow, so that it would show up in the same spot on every page of the resulting pdf ?

Thanks for this immensely helpful package.

**Comment by gulien** [comment]
Hello @adame21 

> Is it possible to somehow force the result pdf to be just 1 page? can I at all control how gotenberg will split the html ?

Gotenberg is a sort of proxy API between your client and Google Chrome. The only way to control that kind of stuff is by JavaScript/CSS etc., but that's not bullet proof.

> I couldn't understand well enough from the docs how to send a font, I messed around but couldn't use a font file and not a uri to the font. does it have to be a .woff file ? can .ttf be used ?

You could either install the fonts in the Docker image (`.ttf` or `apt-get install yourfont`), or send them as assets with some CSS, or use a Google fonts URL.

> is it possible to designate a background image somehow, so that it would show up in the same spot on every page of the resulting pdf ?

It should be feasible with a CSS property.

**Comment by adame21** [comment]
I understand, I'll look into css solutions, and pester our devops for the fonts :)

Thank you very much.
