### ISSUE TITLE
Gotenberg ignoring my margin configurations

### ISSUE THREAD

**Issue by adame21** [thecodingmachine/gotenberg#270]
Hello,

I am using 2 completely different instances of Gotenberg, one for my local dev usage, another for actual use in kubernetes.

The one I'm using locally isn't really in my control, and as far as I know its a completely default gotenberg instance.

The local gotenberg seems to work right, while the one hosted on our kubernetes and is used there, seems to ignore the margins I send it (and defaults to 1 inch).

The only differences between the two are these:
MAXIMUM_WAIT_TIMEOUT: "180"
DEFAULT_WAIT_TIMEOUT: "180"
LOG_LEVEL: "DEBUG"

I'm using nodejs with gotenberg-node-client, but this is the same for local and kubernetes env, so I don't think I can fault the client.

Other than that I guess its just how much memory and cpu im allocating it but I cant imagine thats relevant.

Any leads on what I'm doing wrong?
Gotenberg is an amazing solution either way and I'm immensely thankful.

**Comment by gulien** [comment]
Hello @adame21 

No idea, maybe not the same version of Gotenberg? Maybe not the exact same version of gotenberg-node-client?

**Comment by adame21** [comment]
Hi,
Gotenberg version might be a great direction.
Our gotenberg is always using latest while the other one was deployed ~3-4 months ago and wasnt updated since then
I'll look into the good gotenberg version.
Keeping open untill I check and update
Thanks !

**Comment by adame21** [comment]
Hello,
So I am here to update on what fixed it.
It indeed was the version, upon downgrading the issue was resolved.
The version that was giving the issue: 6.3.1 - 3 months old
The version the is now working properly: 6.3.0 - 6 months old
Am closing as well.
Thanks !
