### ISSUE TITLE
Power Automate Support

### ISSUE THREAD

**Issue by TargetCrafter** [thecodingmachine/gotenberg#271]
## Expected Behavior
The documentation does not describe how to use this in applications such as Microsoft's Power Automate. I understand that you can't make documentation for each platform, but this seems like a perfect usecase for a project like this.

## Current Behavior
No documentation is available for Microsoft's Power platform

## Possible Solution
Import the curl command to postman, then export this to a Microsoft Power Automate custom connector. but you seem to miss data for this to work..

## Context
I am trying to make a Powerapps application to convert a filled in word document to PDF to send it off to a printer. I wanted to get rid of a payed API and host my own, an then i came across this. I have it working in Postman, but im not able to get it working in Microsoft Power Automate, which as HTTP support.

## Your Environment
* Version used: 6.3.1
* Operating System and version: Docker on a Synology NAS

**Comment by gulien** [comment]
Hello @TargetCrafter,

I dunno how Microsoft's Power Automate works, and unfortunately I do not have have time currently to investigate on this.
If you find a solution, I'll gladly accept a PR that update the documentation 😄

**Comment by TargetCrafter** [comment]
Power Automate uses JSON to create the body, so you'd have to make the form-data yourself.
![image](https://user-images.githubusercontent.com/47614276/104201121-b14df280-5429-11eb-9dc3-b5840b232083.png)

If this is too much to go into at the moment i understand, then i'll have to go find another solution...
