### ISSUE TITLE
Render order

### ISSUE THREAD

**Issue by adame21** [thecodingmachine/gotenberg#272]
Hi,

I am using two files, index.html and header.html.
Index is just some html page, the header is just used to plant a logo on every page.

It seems the header gets rendered first, and then the index page is rendered over the header, covering some of it.

Is it possible to change the render order on the pdf?
To make sure the logo will appear on top every time.

It seems the css between them is unrelated so I wasn't able to use z-index.

Any other idea to achieve this goal? (header over index)

Thanks :)

**Comment by gulien** [comment]
I do not think that the header is rendered below the main content. Did you try to increase the size of the image?

**Comment by gulien** [comment]
For instance, text have to use a bigger font size in order to be visible in the header.

**Comment by adame21** [comment]
Yeah, I can definitely see the logo showing behind the index.html, cropped rectangularly, I'll try to upload a screenshot somehow but im in an enterprise environment.

**Comment by adame21** [comment]
Well I played around and no luck.
To anyone arriving here heres what I did:
Simply convert the page, and then add logos/header/footer/etc at the pdf processing level (with another lib dedicated to this)
Thanks ! :)

**Comment by hashkazi00** [comment]
what do you mean by pdf prcessing level here? any pointers on how you solved it?
