### ISSUE TITLE
Merge unordered

### ISSUE THREAD

**Issue by IlliaHreben** [thecodingmachine/gotenberg#280]
## Expected Behavior
Expect the first file in multipart form-date to be the first page in the document.

## Current Behavior
Now files are merged in random order.

## Steps to Reproduce
1. Set this two files to multipart form-data , or other files, that you want to reproduce. 
[Povidone Iodine_Lake Erie Medical_USA_PI_In-Draft_10-Feb-2021_en_0.0-0.1.pdf](https://github.com/thecodingmachine/gotenberg/files/5971952/Povidone.Iodine_Lake.Erie.Medical_USA_PI_In-Draft_10-Feb-2021_en_0.0-0.1.pdf)
[725ffbdd-3075-47cd-9ae3-eb01daa18d86.pdf](https://github.com/thecodingmachine/gotenberg/files/5971953/725ffbdd-3075-47cd-9ae3-eb01daa18d86.pdf)
2. Send request
3. Change files order in multipart form-data and send request again. Expect files in merged document unordered.

## Logs
{"bytes_in":"187158","bytes_out":"184226","host":"localhost:3001","latency":"73926684","latency_human":"73.926684ms","level":"info","method":"POST","msg":"request handled","op":"context.Context.LogRequestResult","path":"/merge","referer":"","remote_ip":"172.18.0.1","status":200,"time":"2021-02-12T13:04:44Z","trace":"iSTr3u2gJoaxQzCC4JFlF8TwXWpL4eii","uri":"/merge","user_agent":"insomnia/2020.4.2"}

## Your Environment
* Version used: 6
* Operating System and version: ubuntu 20.04

**Comment by gulien** [comment]
Hello @IlliaHreben,

Gotenberg merges the PDF files alphabetically. See: https://thecodingmachine.github.io/gotenberg/#merge.basic
