### ISSUE TITLE
local file inclusion via /convert/url remoteURL endpoint

### ISSUE THREAD

**Issue by NoRelect** [thecodingmachine/gotenberg#283]
## Expected Behavior
When attempting to convert html into a PDF using the `/convert/url` endpoint, gotenberg should throw an exception (respond with a bad request) whenever there is an attempt to convert from an url with a scheme that is not `http://` / `https://`.
[HTTP POST] `/convert/url`
[PARAM] form: `remoteURL=file:///etc/passwd`
[RESPONSE] 400 Bad Request

## Current Behavior
[HTTP POST] `/convert/url`
[PARAM] form: `remoteURL=file:///etc/passwd`
[RESPONSE] PDF with contents of /etc/passwd

## Possible Solution
Whitelist the allowed schemes that can be passed to the API endpoint to `http://` / `https://`.

## Steps to Reproduce (for bugs)
1. Start the latest version of gotenberg (at this time, v6.4.0)
```
docker run --rm -p 3000:3000 thecodingmachine/gotenberg:6.4.0
``` 
2. Send a request with the remoteUrl parameter set to a local file:
```sh
curl --request POST \
    --url http://localhost:3000/convert/url \
    --header 'Content-Type: multipart/form-data' \
    --form remoteURL=file:///etc/passwd \
    -o localFileIncluded.pdf
```
3. Read the file contents from the pdf:
![gotenberg_lfi](https://user-images.githubusercontent.com/17455811/109473775-0befec00-7a74-11eb-8df4-199382fac549.png)

## Context
Reading an arbitrary file from within the container is a security vulnerability.
There is a another local file inclusion vulnerability already existing that works via Iframes (https://github.com/thecodingmachine/gotenberg/issues/261).

## Environment
* Version used: 6.4.0
* Operating System and version: Linux Container

**Comment by gulien** [comment]
Thanks @NoRelect 

This is a known issue and it should be resolved in the next version.

In the meantime, as stated in the documentation:

> Gotenberg should ONLY be used in a trusted network by trusted applications. Do NOT expose Gotenberg to the external world.

You're also welcome to provide a PR for this version :)
