### ISSUE TITLE
unoconv GPL license

### ISSUE THREAD

**Issue by pawepaw** [thecodingmachine/gotenberg#287]
Hi,

How is it possible that you're using `unoconv` which has GPL-2 license and you're exposing `gotenberg` as MIT? Do you have some special agreement with `unoconv` or am i missing something?

**Comment by gulien** [comment]
Hello @pawepaw, no I don't. 

@dagwieers or @regebro: if there is an issue on that matter, feel free to contact me 😃

**Comment by pawepaw** [comment]
Well wanted to use it but the GPL license disqualifies my usage plan, probably more users would have the same problem if they spot that they are actually using GPL soft, not MIT.

Would be good to clarify it.

**Comment by dagwieers** [comment]
IANAL. I don't think there is a problem. AFAICT unoconv is called as an external tool for performing the conversion.
There could have been issues if it would be calling unoconv as a library, but that is not the case here IMO.

**Comment by gulien** [comment]
Thanks @dagwieers for the clarification 👍

**Comment by pawepaw** [comment]
Well i'm not a lawyer as well :D thanks for fast answers!
