### ISSUE TITLE
Update latest release image to use Debian 10.8

### ISSUE THREAD

**Issue by wattcode** [thecodingmachine/gotenberg#290]
Unable to find existing issue.

## Expected Behaviour
When pulling the latest image from docker hub, using the command below. 

`docker run --rm -p 3000:3000 thecodingmachine/gotenberg:6`

The resulting base OS is Debian 10.8. 10.8 contains a number of security patches and bug fixes, see the release document for details.

https://www.debian.org/News/2021/20210206

## Current Behaviour
The resulting base OS is Debian 10.7

## Possible Solution
Re-run the release pipeline

## Steps to Reproduce (for bugs)
1. `docker run -p 3000:3000 thecodingmachine/gotenberg:6`
2. `docker exec -it {image_id} /bin/shh`
3. `cat /etc/debian_version`

## Context
A recent security test on our platform highlighted issues with Debian 10.7 resolved by 10.8. We've since created a patched version of the image ourselves. However, I wanted to make you aware of the issue in case you wanted to create a public patch.

## Your Environment
* Version used: 6.4.0
* Operating System and version: N/A
* Link to your project: N/A

**Comment by gulien** [comment]
Hello @wattcode,

I've triggered a new build (`6.4.1`) of the image and that should resolve most of the issues 😄 

Yet, could you share what did you patch in the image? It seems there are still some vulnerabilities (see https://github.com/thecodingmachine/gotenberg/issues/291#issuecomment-806149123).

**Comment by wattcode** [comment]
Hey, I've just checked the latest image you've pushed and it has pulled in the latest version of `debian (buster) 10.8` which is exactly the change we made. 😃 

![image](https://user-images.githubusercontent.com/12176844/112483146-ab04bc80-8d70-11eb-8bd3-af636be1bf3e.png)

As to the other security issues mentioned in comment #291 I'm unable to comment. We haven't picked up on any additional issues in 10.8. However, we haven't run a vulnerability scan on this image since the update. Perhaps they can privately give you more details as to the vulnerabilities raised? Happy to close this ticket now, as the expected behaviour has been met.

**Comment by Marvedog** [comment]
The other vulnerabilities are those patched in the recent version upgrade of the Buster image. https://www.debian.org/News/2021/20210327 @gulien

**Comment by gulien** [comment]
I need to put a weekly / monthly automatic release system for those 🤔

**Comment by Marvedog** [comment]
Yeah, that would be less work :+1: Monthly would suffice though I guess
