### ISSUE TITLE
Chrome known vulnerabilities

### ISSUE THREAD

**Issue by Marvedog** [thecodingmachine/gotenberg#291]
## Expected Behavior
Possibly patch up the chrome image in v6.4.0.

## Current Behavior
Tons of possible vulnerabilities found in chrome prior to version 89.0.4389.90.

## Possible Solution
Release the version with the latest chrome image.

## Steps to Reproduce (for bugs)
n/a

## Logs (LOG_LEVEL="DEBUG")
n/a

## Context
Scanned using the built-in Docker image scanner in Azure Security Center.

## Your Environment
n/a

**Comment by Marvedog** [comment]
@gulien It seems to me that you just use the latest chrome version which should be equal to or greater than 89.0.4389.90. If so, that should resolve the issue. This will also resolve #290 btw, since it also seems like you just use the latest debian image as well :)  

Correct me if I am wrong here about the chrome and debian dependencies.

**Comment by gulien** [comment]
I've create a new release for triggering a build :) once deployed, can you tell me if that's OK for you?

**Comment by Marvedog** [comment]
Sure thing!

**Comment by Marvedog** [comment]
Yupp, the vulnerabilities with the chrome version is resolved. At least from the results in our scanner :) Some of the Debian vulnerabilities persists though, but those are addressed in #290 I guess.

**Comment by gulien** [comment]
Thanks @Marvedog 👍
