### ISSUE TITLE
When paged, the data display is incomplete

### ISSUE THREAD

**Issue by TonyMistark** [thecodingmachine/gotenberg#30]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Expected Behavior
Convert HTML to a PDF file, and page after page is displayed

## Current Behavior
There is a probability that the data between the two pages is incomplete and half of it is erased
[ill pdf file](https://github.com/TonyMistark/temp_file/blob/master/html_convert_to_pdf_issues.pdf)
## Steps to Reproduce (for bugs)

1.create a table HTML, more than one page
2.convert HTML to pdf

## Your Environment

* Version used:1.11.2
* Operating System and version:ubuntu 16.10
* Link to your project:

**Comment by gulien** [comment]
It may be possible to use some CSS properties to fix this? Or reduce margins?
