### ISSUE TITLE
6.4.2 causes incorrect docx -> pdf conversion

### ISSUE THREAD

**Issue by ryanshow** [thecodingmachine/gotenberg#301]
## Expected Behavior

Given a docx file, I expect that the generated PDF should look reasonably similar to how LibreOffice renders it on my desktop. (same fonts, same font sizes, etc).

## Current Behavior

After upgrading to 6.4.2, a few of the documents I convert have different fonts and sizes. In particular, many of the headers look to be enlarged by at least 2 points and are being rendered in a completely different font.

## Possible Solution

6.4.1 works fine. I see that there were a bunch of changes to the image made in 6.4.2 in an attempt to reduce the image size. I'm guessing some fonts may be missing, or perhaps something else that LibreOffice depends on.

## Steps to Reproduce (for bugs)

1. Create a docx file with some text having the Calibri font size 14
2. Convert it to PDF

**Comment by gulien** [comment]
@bendavies could it be related to the different fonts version?

<img width="1416" alt="Capture d’écran 2021-04-14 à 16 20 52" src="https://user-images.githubusercontent.com/8983173/114726144-6354cd80-9d3d-11eb-9bf3-786cf6bfdd47.png">

**Comment by bendavies** [comment]
it seems the old install method installed version `3.7` of `ttf-mscorefonts-installer`, and now we install `3.8`. 
however, i've just compared and they seem to install the same fonts to me, both coming from sourceforce.

**Comment by bendavies** [comment]
if it's libreoffice, i would the difference between the installed packages these, since we added `--no-install-recommend`
`apt-get -t buster-backports -y install libreoffice`
vs
`apt-get --no-install-recommends -t buster-backports -y install libreoffice`

**Comment by bendavies** [comment]
https://wiki.debian.org/SubstitutingCalibriAndCambriaFonts

so this may be resolved by installing `fonts-crosextra-carlito` + `fonts-crosextra-caladea`, which is in my list above.

**Comment by gulien** [comment]
Good catch with the extra fonts!

@ryanshow could you try to install these fonts and see if it resolves your issue?

**Comment by ryanshow** [comment]
I can confirm that installing `fonts-crosextra-carlito` and `fonts-crosextra-caladea` works great. Thanks everyone!

I would suggest that all of the missing fonts packages be installed to ensure maximum compatibility.

**Comment by gulien** [comment]
I do agree :)

Anyone of you want to make a PR?
