### ISSUE TITLE
Add support to convert a URL to PNG or PDF

### ISSUE THREAD

**Issue by hjjg** [thecodingmachine/gotenberg#38]
Hey guys, 

you really did a great job! Love the webhook feature!

Now that you already spawned a headless instance of Chrome, how about taking an URL to take a screenshot of a web page (with configurable view port size) or printing to PDF? It would make my live easier!

Thanks and regards,

hjjg

**Comment by gulien** [comment]
Glad you like it 😄 

Actually there is already a Docker image for creating PDF from URLs: https://github.com/arachnys/athenapdf

IMO not sure this should be included in Gotenberg (maybe a bit out of scope?).

**Comment by nileshcs** [comment]
Please let me know if PNG image generation is supported from a web URL. I was not able to find that in the documentation even though release 4.0.0 says this feature may be available. @gulien

**Comment by gulien** [comment]
Hello @nileshcs,

No, Gotenberg is not able to generate an image from a web URL 😶

I understand the use case though, but right now I'd prefer Gotenberg to stick to PDF 😅

See also #110
