### ISSUE TITLE
Deployment tips in docs

### ISSUE THREAD

**Issue by karakanb** [thecodingmachine/gotenberg#40]
Hey guys, thanks a lot for this amazing project, you are doing an amazing job with it.

So far I am using it to convert PPTX files to PDF, but right now my deployed version seems to be much slower than local version. I am running Gotenberg with k8s, and my problem is, one sample PPTX file is converted to PDF in 25s on my deployed version, and 4s on my local machine. I have tried doubling the resources on k8s and the PDF creation came to 13s, which is half of the previous version, but this way I am giving it more and more resources, which is still not as good as my local + horizontal scaling becomes more expensive.

Since you guys seem to be running this for a while, you probably have some best-practices around how to deploy this and what are the optimum resource requirements, etc.. It would be great if you can include your tips in the documentation, whether making the service run faster by disabling something or excluding some binary for some use cases for example, or the resource requirements for the sweet spot between performance and scalability. If this is out of scope for you I can try to write some docs in a PR, but it would be much easier using your experience with it rather than me inspecting every moving piece.

**Comment by gulien** [comment]
Hello @karakanb! Glad you like it 😄 

Not sure where the bottleneck is in your case.

For Office conversions we rely on unconv + Libreoffice so increasing your memory and CPU requests/limits seems the way to go.
 
There are also some I/O operations going on when converting a document to PDF, so maybe your local machine has a more efficient SSD?

**Comment by karakanb** [comment]
It is possible, but I am not sure the disk IO is the bottleneck here as increasing CPU & RAM requests sped up the process, so it seems like bottleneck is CPU or RAM here. In my case I am only using it for converting PPTX > PDF, so if there is a possibility to disable some services it might also be beneficial in terms of resource usage. Maybe we can disable some services on boot time based on some ENV variables? I literally have no clue if that is doable or not, just throwing some ideas. 

Still, it would be nice to have your recommendations regarding deployment in the docs as those would be meaningful starting points for most of the use cases, for example the part about unoconv and horizontal scaling was a great tip. 

Again, thanks for all the amazing work. 🎉
