### ISSUE TITLE
update the Dockerfile , Which Dockerfile is built? In the build folder

### ISSUE THREAD

**Issue by dengwoadeng** [thecodingmachine/gotenberg#43]
I have to update the Dockerfile in order to support Chinese characters.
but I do not know   Which Dockerfile is built? In the build folder ,There are many Dockerfiles
![image](https://user-images.githubusercontent.com/34929719/51814077-7f066180-22f4-11e9-87f1-e29c5dc93cdf.png)

**Comment by Sten-H** [comment]
Have a look in the Makefile in the root directory. Specifically under "Build docker image" comment. 

As I understand it, it will first build the base image (build/base/Dockerfile) and then it will build from build/package/Dockerfile which will use the new base image (FROM thecodingmachine/gotenberg:base)

**Comment by gulien** [comment]
Actually there is no need to update those files directly: simply create your own Dockerfile!

```
FROM thecodingmachine/gotenberg:3.2.0

// do your stuff here
```

**Comment by dengwoadeng** [comment]
Thank you! I have succeeded build a new container,and update the Dockerfile
![image](https://user-images.githubusercontent.com/34929719/51824962-af62f580-231e-11e9-9fb4-9135761fad02.png)
![image](https://user-images.githubusercontent.com/34929719/51824966-b427a980-231e-11e9-8bca-6d3632d9683b.png)
but When exporting PDF, Chinese Still garbled
![image](https://user-images.githubusercontent.com/34929719/51825095-01a41680-231f-11e9-8780-2a0c7ba77501.png)
How can I solve it? Please tell me, thank you

**Comment by gulien** [comment]
I guess you need to install the missing Chinese fonts.
This link might help you: https://help.accusoft.com/PrizmDoc/v12.1/HTML/Installing_Asian_Fonts_on_Ubuntu_and_Debian.html

**Comment by dengwoadeng** [comment]
Thank you!!!   Successfully output Chinese

**Comment by gulien** [comment]
Great! Have fun 😄
