### ISSUE TITLE
[BUG] HTML-to-PDF sometimes lose some parts of HTML

### ISSUE THREAD

**Issue by server-may-cry** [thecodingmachine/gotenberg#44]
## Expected Behavior

PDF generated from HTML contain all elements of HTML.

## Current Behavior

Sometimes (1 of 10 in average) parts of HTML elements lost in resulted PDF. Biggest problem is that response status code is 200.

## Steps to Reproduce (for bugs)

1. Create `index.html` with content https://gist.github.com/server-may-cry/57b062186f648a16f6e4c5c7ac354e38
2. `curl --request POST --url http://gotenberg:3000/convert/html --header 'Content-Type: multipart/form-data' --form files=@index.html -o result.pdf`
3. See file size
4. Repeat 10-20 times each time check file size

## Context

No difference in logs from container for failed and ok requests
```
ok
gotenberg_1                | {"time":"2019-01-28T17:56:49.563200149Z","id":"","remote_ip":"172.18.0.16","host":"gotenberg:3000","method":"POST","uri":"/convert/html","user_agent":"curl/7.52.1","status":200,"error":"","latency":423976853,"latency_human":"423.976853ms","bytes_in":8501,"bytes_out":28024}

failed
gotenberg_1                | {"time":"2019-01-28T18:02:20.799825196Z","id":"","remote_ip":"172.18.0.16","host":"gotenberg:3000","method":"POST","uri":"/convert/html","user_agent":"curl/7.52.1","status":200,"error":"","latency":566488490,"latency_human":"566.48849ms","bytes_in":8501,"bytes_out":28024}
```

## Your Environment

* Version used: tested on 3.2 and 4 (on version 4 it happens very rarely)
* Operating System and version: docker image
* Link to your project:

**Comment by gulien** [comment]
Hello @server-may-cry!

I'll try to reproduce your issue in order to find the root cause.
I'm currently a bit busy, so it might take some time.

**Comment by gulien** [comment]
Ok so I think I've found what's going on.

As you're using a Google font with a lot of different weights/styles, it's kind of heavy to load:

<img width="587" alt="capture d ecran 2019-01-31 a 09 37 36" src="https://user-images.githubusercontent.com/8983173/52041870-f24de480-253b-11e9-9504-0d1cb0d375af.png">

I've created a simple script to generate 100 PDFs and "only" two had an issue.
Using a "normal" font like Arial drop this number to 0.

**Workaround :**  you should use less weights/styles.

**Comment by server-may-cry** [comment]
Thank you @gulien
Could I configure and increase allowed time to load fonts?
Or return different HTTP status code when this error happens.

**Comment by gulien** [comment]
Actually Gotenberg should be waiting for the fonts to be loaded and return an error otherwise: https://github.com/thecodingmachine/gotenberg/blob/master/internal/pkg/printer/html.go#L106.

It "works" because without those lines web fonts are not loaded. BUT it seems that sometimes the fonts are loaded but not yet rendered. Not sure how to mitigate this issue ^^

**Comment by server-may-cry** [comment]
Is it our timeout `setTimeout(resolve.bind(resolve, 'timeout'), %.0f);` ?
https://github.com/thecodingmachine/gotenberg/blob/master/internal/pkg/printer/html.go#L110 ?

Maybe it should be like
```js
	new Promise((resolve, reject) => {
		document.fonts.ready.then(function () {
			resolve('fonts loaded');
		});
		setTimeout(reject.bind(reject, 'timeout'), %.0f);
	});
```

**Comment by gulien** [comment]
@server-may-cry new version 4.1 should now work as expected: you may update the timeout with the form field webFontsTimeout (in ms).

**Comment by set-webmaster** [comment]
Would there be a way to add a delay not only for fonts but for other content too? I'm trying to generate a pdf from an html page that spans hundreds of pages, and it returns a blank file as the content doesn't have time to load that the generator is already done converting...

**Comment by gulien** [comment]
Alright ! But please open a new issue :)
