### ISSUE TITLE
Kitematic: manifest not found

### ISSUE THREAD

**Issue by tobwen** [thecodingmachine/gotenberg#48]
## Expected Behavior
I'd like to download and run Gotenberg in https://kitematic.com/ on Windows.

## Current Behavior
> (HTTP code 404) unexpected - manifest for thecodingmachine/gotenberg:latest not found

## Steps to Reproduce (for bugs)
1. Install Docker Toolbox on Windows with Kitematic
2. Click "New"
3. Search for "Gotenberg"
4. Click "Create"

## Context
Kitematic is a GUI to easily run Docker images on Windows (in connection with Docker Toolbox, it uses VirtualBox for virtualizing the base OS)

## Your Environment
1. Windows 7 Pro 64bit, Windows 10 Pro 64bit (both latest)
2. Kitematic & Docker Toolbox (latest)

**Comment by gulien** [comment]
I could tag a `latest` release, but isn't it possible to specify a custom tag in Kitematic?

**Comment by tobwen** [comment]
Yeah, but "latest" go soooo much easier :) Thanks a lot!
