### ISSUE TITLE
environment variable to switch on/off engines

### ISSUE THREAD

**Issue by tobwen** [thecodingmachine/gotenberg#49]
Would it be possible to insert an environment variable to turn on/off LibreOffice or Chrome support? Sometimes, I don't need Chrome, so I want to save resources.

**Comment by gulien** [comment]
We could also provide a "slim" image which contains only the basics and then thanks to Docker multi-stage build:

```Dockerfile
ARGS ENABLE_CHROME=1
FROM thecodingmachine/gotenberg

// the previous args will automatically triggers the installation of Chrome.
```

**Comment by tobwen** [comment]
I'd really love that. Unfortunately, I probably can't help with the implementation.

**Comment by thomasf** [comment]
I would maybe also like if the service processes can be configured to be started lazily and shut down the processes if they haven been used for a configurable duration.. I have a lot very low activity low resource  staging environments where this would be very handy.

**Comment by gulien** [comment]
Great idea! 👍
