### ISSUE TITLE
go mod incompatibility

### ISSUE THREAD

**Issue by trelore** [thecodingmachine/gotenberg#54]
Trying to use this module in other a go mod enabled repo of us is causing issues with some of the unused dependencies (particularly delve). Running `go mod tidy` fixes these issues.

## Expected Behavior
`GO111MODULE=on go get -u github.com/thecodingmachine/gotenberg@4.2.0`
Should allow us to use the go module.

## Current Behavior
The gotenberg module is marked as incompatible.

## Possible Solution
run `go mod tidy`

## Context
We are unable to use the go module for talking to the gotenberg service in our k8s cluster.

I have a commit ready on a [fork](https://github.com/tumelohq/gotenberg). Wanted to raise an issue first, happy to raise PR if accepted.

**Comment by gulien** [comment]
Yes please feel free to open a PR 👍 

I'll tag a new version (4.2.1).

**Comment by trelore** [comment]
As a slight aside to this, I noticed the release tags changed from `vX.X.X` to `X.X.X`, go mod to my understanding defaults to looking for `vX.X.X` releases, meaning without looking into the repo to specifically grab the latest, we're going to be getting for `v2.0.0`. Im unsure on the change to strip the `v`, nor the consequences of going back to `vX.X.X`. Further reading; https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-v2-package-that-has-not-opted-into-modules-what-does-incompatible-mean .

My understanding on this might be wrong though.

I'll make the PR now. Cheers

**Comment by gulien** [comment]
@trelore does the 4.2.1 tag resolve your issue?

Also, I'm not sure to understand the issue with go mod. I've never used `vX.X.X` as tags but `X.X.X`. 🤔

**Comment by trelore** [comment]
Looks like it fails silently. Modules is still a bit of a dark art for me, but the following happens;

Running `GO111MODULE=on go get -u github.com/thecodingmachine/gotenberg` or `GO111MODULE=on go get -u github.com/thecodingmachine/gotenberg@4.2.1`
Creates the entry `github.com/thecodingmachine/gotenberg v2.0.0+incompatible // indirect` in go.mod.
Running `GO111MODULE=on go mod download` & `GO111MODULE=on go mod vendor` then doesn't add the repo to our vendor dir

Running  `GO111MODULE=on go get -u github.com/thecodingmachine/gotenberg/pkg`
Fails outright

Running `GO111MODULE=on go get -u github.com/thecodingmachine/gotenberg/pkg@4.2.1`
Updates go mod file with `github.com/thecodingmachine/gotenberg v0.0.0-20190313095320-ab78559710f4` (note version is set to 0.0.0, because the version is 2 or higher, in my understanding this is part of a compatibility thing)
Running `GO111MODULE=on go mod download` & `GO111MODULE=on go mod vendor` then brings the v4.2.1 pkg codebase into our repo. Which is the intended goal, however as gotenberg updates, we need to manually update our dependency.

To my understanding tagging `vX.X.X` would mean the second attempt would work, but I'm not 100% confident.

**Comment by gulien** [comment]
> Modules is still a bit of a dark art for me

Same here! I'm a bit lost. I'll come back to you as soon as I've find a correct solution (as you said, tagging `vX.X.X` may work but I want to understand whats going on 😄).

**Comment by gulien** [comment]
Ok I'm lost for good : https://github.com/golang/go/issues/27009

So the last version of Gotenberg without `go.mod` was `v2.0.0`:

```
Code written before the semantic import versioning convention
was introduced may use major versions v2 and later to describe
the same set of unversioned import paths as used in v0 and v1.
To accommodate such code, if a source code repository has a
v2.0.0 or later tag for a file tree with no go.mod, the version is
considered to be part of the v1 module's available versions
and is given an +incompatible suffix when converted to a module
version, as in v2.0.0+incompatible. The +incompatible tag is also
applied to pseudo-versions derived from such versions, as in
v2.0.1-0.yyyymmddhhmmss-abcdefabcdef+incompatible.
```

I've removed it (there was no library for this version) and was expecting go mod to be able to retrieve the latest version, but alas it's not working:

```bash
$ go clean --modcache
$ go list -m -versions -f '{{join .Versions "\n"}}' github.com/thecodingmachine/gotenberg
go: github.com/thecodingmachine/gotenberg@v2.0.0+incompatible: unknown revision v2.0.0
```

Not sure what to do next.

**Comment by gulien** [comment]
It was a cache issue. Now running `go get -u github.com/thecodingmachine/gotenberg` creates the entry `github.com/thecodingmachine/gotenberg v0.0.0-20190313095320-ab78559710f4 // indirect`.

**Comment by gulien** [comment]
@trelore I think the best option would be to create a separate repository for the Go library.

Something like:

```
module github.com/thecodingmachine/gotenberg-go-client/v4
```

And when Gotenberg 5.0.0 is released:

```
module github.com/thecodingmachine/gotenberg-go-client/v5
```

**Comment by trelore** [comment]
Yeah, I was thinking about that. From a third party perspective they seem like 2 distinct offerings. Bundling them together gives tight coupling when it comes to releasing fixes for one or the other.

**Comment by gulien** [comment]
@trelore the new client is now available at https://github.com/thecodingmachine/gotenberg-go-client! 😄

**Comment by gulien** [comment]
@trelore does this resolve your issue?

**Comment by trelore** [comment]
Apologies, looked at this last night and forgot about it.
Works perfectly fine, happy for this to be closed 👍

**Comment by gulien** [comment]
Np 😄 Great to hear 👍
