### ISSUE TITLE
Add a parameter specifying the resulting pdf filename

### ISSUE THREAD

**Issue by sqrter** [thecodingmachine/gotenberg#56]
## Expected Behavior
Hi guys! Would it be possible to add a parameter specifying the resulting pdf filename after converting from html/url?

## Current Behavior
Response Headers always include a random filename, e.g `content-disposition: attachment; filename="73952a7767eb9af0c94c05e525c7f327.pdf"`

## Possible Solution
I'd suggest adding a new parameter in addition to the existing ones (remoteURL, webhookURL, paperWidth, paperHeight, etc), e.g. "fileName", so that users can define custom value.

## Context
In real world it would allow consumer of the gotenberg api, e.g. html page to perform a POST request using an html form and expect Save File dialog to appear with correct file name populated, instead of seeing some random name.

**Comment by gulien** [comment]
IMO you should not expose directly the Gotenberg endpoints 🤔 - it's not secure.

Using the Go or PHP library you may retrieve the response from Gotenberg and change the filename on the fly.

**Comment by sqrter** [comment]
Actually I was thinking to put Nginx in between but rather using the api without any intermediate app server..

**Comment by gulien** [comment]
Fair enough!

**Comment by gulien** [comment]
@sqrter Hope it solves your issue :)
