### ISSUE TITLE
Blank document generated

### ISSUE THREAD

**Issue by set-webmaster** [thecodingmachine/gotenberg#58]
## Expected Behavior
Document should be generated as closely as what's displayed in browser as possible

## Current Behavior
Generated document is completely blank (empty)

## Possible Solution
Adding a possibility to specify a delay to let the page load completely before performing the actual conversion. 

What could be even better would be to add a mechanism similar to what Puppeteer uses with the *waitUntil* option (see their [documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md)) in the page.goto section [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options)

## Steps to Reproduce (for bugs)
1. Using the `convert/url` endpoint
2. Specify an url that corresponds to a page on which the html spans multiple physical pages in length
3. Send the request

## Context
Trying to generate a pdf from an html page that would essentially span close to 100 pages in PDF format.

## Your Environment
* Version used: 4
* Operating System and version: Windows 10, latest stable build

**Comment by gulien** [comment]
@set-webmaster could you send me the URL of the paye you're trying to generate?

**Comment by set-webmaster** [comment]
Sadly I can't share it as it's from an internal app I'm working on. But, if the problem is effectively that some items are delayed and the conversion runs too fast, anything that is delayed on purpose would recreate the same use case. 

Here is a quick example you can use that should recreate this issue in a certain way (only the content initially available will be displayed. See [here](https://jsfiddle.net/Os1r1s110/6hdf895q/10/show)

**Comment by gulien** [comment]
Thank you for the feedback 👍 

Actually it's not the same issue.

In the new version of Gotenberg, I'm watching for more events, one of them being `DOMContentLoaded`. So in your case, Gotenberg will wait until your 120 000 lines of HTML are loaded (except if it takes more time than a timeout you may define).

But in your example, it's a javascript delay and as far as I know there is no event 
for handling such cases.

I've ended adding a "sleep" which make it works though. It should be OK, as each requests are handled by a goroutine and the sleep only "pause" the execution of the considered goroutine.

**Comment by set-webmaster** [comment]
Yeah as I said it is effectively not the exact same issue (one caused by long content loading delay, the other being Javascript induced).

A potential solution for Javascript induced delay (like react apps or other frontend frameworks that render content dynamically) would be to add a way to await for a certain selector (such as what's done in Puppeteer, see [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectorselector-options)

Waiting for the DOMContentLoaded is a better solution than the delay and that will be an excellent addition IMO.

Do you have any estimate of the availability of the "new version"?

**Comment by gulien** [comment]
Indeed, the wait selector seems to be a good option. Not sure how to implement in Go.
For now, I'll simply add a `delay` form field :)

The new version should be available soon, it's almost done.
I need to update the clients though.

**Comment by set-webmaster** [comment]
Sorry if it's supposed to be easy to find, but would you mind telling me where the `DOMContentLoaded` event is treated? Is it [here](https://github.com/thecodingmachine/gotenberg/blob/571c3e04c40c924be05824049c0ddca04b36208a/internal/pkg/printer/html.go#L90)? I can't find the actual `DOMContentLoaded` anywhere...

Thanks in advance!

**Comment by gulien** [comment]
#66
