### ISSUE TITLE
Is authentication planned ?

### ISSUE THREAD

**Issue by Grafikart** [thecodingmachine/gotenberg#60]
First I want to thank you for this, it just work out of the box and it's well documented. 

But I wanted to know if it was plan to create an authentication system for gotenberg so it could be exposed as a service directly.

```
docker run --rm -p 3000:3000 thecodingmachine/gotenberg:4 gotemberg
JWT_KEY='myJWTKey'
```

Feel free to close this issue if you think it's out of the scope of gotenberg and should be handled by a proxy for instance.

**Comment by gulien** [comment]
Hello @Grafikart 

IMO it's out of the scope of Gotenberg 😄 as you saif it should be handled by a proxy 👍
