### ISSUE TITLE
the merge out-of-order issue

### ISSUE THREAD

**Issue by systemcia** [thecodingmachine/gotenberg#63]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Expected Behavior

when i merge three or more pdf files , the result pdf should be ordered . for example : i merge 1.pdf , 2.pdf ,3.pdf , 4.pdf , the sum pdf file should be 1,2,3,4 turn ,the asc order. 
## Current Behavior

i got the result pdf ,which have the 2,4,1,3 turn  , it's out-of-order
## Steps to Reproduce (for bugs)

1.prepare three or more pdf files , 1.pdf , 2.pdf ,3.pdf,4.pdf
2.request the merge feature
3.check the order of the result pdf
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by gulien** [comment]
Hello @systemcia!

Weird, I'll try to reproduce it.

**Comment by systemcia** [comment]
> Hello @systemcia!
> 
> Weird, I'll try to reproduce it.

ok , thank you~~
for more information , i have tried: 
it's ok using the curl; 
not ok with the golang client.
