### ISSUE TITLE
Unsure about security

### ISSUE THREAD

**Issue by aurelien-clu** [thecodingmachine/gotenberg#65]
Hello,
Nice work and documentation.

## Expected situation imho

Checking the `Dockerfile` and this repository code should be enough to have a pretty good idea whether this is secured or infected. (e.g. `data leakage`)

## Current situation

In your `Dockerfile`:

```
FROM thecodingmachine/gotenberg:3.2.0 AS hack
```

I am guessing that to reduce your `Dockerfile` you reuse a previous build but... this also hides what your previous build is based on or what is inside it, does not it?

Unless one investigate this particular container and look for issues, which is obviously harder that checking if a `Dockerfile` contains (more obvious) security issues.

## Possible solution

Would it be possible to have a longer `Dockerfile` without any `hack`, some says `explicit is better than implicit` :wink: 

Otherwise I guess I could try to reuse your `Dockerfile` from `tag` 3.2.0 and add it at the top of your latest one.

I am open to hear your point of view, I may be missing something.

**Comment by aurelien-clu** [comment]
Ok I saw your comments in the `Dockerfile` and in https://github.com/Unitech/pm2/issues/4127, I guess I need to verify this previous image :/ (no offense :stuck_out_tongue: )

**Comment by gulien** [comment]
Hello @aurelien-clu 

FYI, the previous `Dockerfile` is actually very close to the current one 😄
