### ISSUE TITLE
Root should return 404 not 500

### ISSUE THREAD

**Issue by hspak** [thecodingmachine/gotenberg#67]
## Expected Behavior
When I query `/`, gotenberg prints
```
{"message":"code=404, message=Not Found"}
```
With an HTTP status code of **404**.

## Current Behavior
When I query `/`, gotenberg prints
```
{"message":"code=404, message=Not Found"}
```
With an HTTP status code of **500**.

## Possible Solution

I imagine this being a one-liner change. I'd be happy to open a PR.

## Steps to Reproduce (for bugs)

1. Query `/`.

## Context
This pollutes logs with `5xx` errors when there's actually nothing wrong.

## Your Environment

* Version used: 4.4.0
* Operating System and version: Any
* Link to your project: N/A

**Comment by gulien** [comment]
#66 fixes this 😉

**Comment by hspak** [comment]
Hey @gulien, it looks like the 6.0.0 regressed on this. Gotenberg throws 500s for missing endpoints instead of 404s again.

**Comment by gulien** [comment]
@hspak sorry for that.

#124 fixes this issue. I've also added some unit tests to prevent such regressions in the future.
