### ISSUE TITLE
PrintToPDF: rpcc: message too large

### ISSUE THREAD

**Issue by shoe-diamente** [thecodingmachine/gotenberg#69]
## Expected Behavior
Attaching small size images should include them in the PDF.

## Current Behavior
Attaching a 32KB image yields:

```
{"time":"2019-05-03T09:15:36.0025674Z","id":"","remote_ip":"192.168.240.7","host":"documents:3000","method":"POST","uri":"/convert/html","user_agent":"","status":500,"error":"code=500, message=printing page to PDF: cdp.Page: PrintToPDF: rpcc: message too large (increase write buffer size or enable compression)","latency":93544042,"latency_human":"93.544042ms","bytes_in":39667,"bytes_out":133}
```

## Steps to Reproduce (for bugs)
1. Start Gotenberg 5.0.1 using the official docker image 
2. Send a cURL request with an image of 32KB+

## Context
I'm trying to add an image to the PDF.

## Your Environment
* Version used: 5.0.1
* Operating System and version: macOS 10.13.6 on the host

**Comment by shoe-diamente** [comment]
It had nothing to do with gotenberg and everything to do with how files were not uploaded correctly.

**Comment by B3nCr** [comment]
We're having the same error. Upload works when running a container locally using docker but we're getting this error in Kubernetes. 

@shoe-diamente can you be more specific?

**Comment by shoe-diamente** [comment]
@B3nCr IIRC the problem was that the image bytes were being embedded in the request payload as opposed to streaming it to the server. Something to do with [this](https://unix.stackexchange.com/a/144483).
