### ISSUE TITLE
Assets accessible in header & footer?

### ISSUE THREAD

**Issue by shoe-diamente** [thecodingmachine/gotenberg#71]
It seems that files (images, stylesheet), passed in via the `files` argument, are correctly accessible in `index.html` but not in `header.html` or `footer.html`. 

How can I embed files in the header or footer?

## Expected Behavior

File accessible in `index.html` are accessible to header and footer as well.

## Current Behavior

It currently doesn't seem to be able to read those files.

## Your Environment

* Version used: thecodingmachine/gotenberg:5 (Docker)

**Comment by gulien** [comment]
Could you share your `header.html` or `footer.html`?

I suspect this is a Chrome limitation...

**Comment by shoe-diamente** [comment]
In my tests the header and footer are like:

```
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="styles.css">
    </head>
    <body>
        <h1 class="red">Hello world!</h1>
        <img src="logo.png" width="200px" />
    </body>
</html>
```

where in `styles.css` there's:

```
.red {
    color: red;
}
```

and what I get is this:

![Screen Shot 2019-05-07 at 14 16 50](https://user-images.githubusercontent.com/40760781/57298595-e2154a80-70d2-11e9-81ab-8ab60cc59eb5.png)

**Comment by gulien** [comment]
Ok I'm pretty sure this is indeed a limitation of Google Chrome.

I've tried to load an image from an URL, it did not work.

For stylesheets, best option would be using the `style` tag instead.

**Comment by shoe-diamente** [comment]
Is this considered expected behaviour (wontfix) or a bug then?

**Comment by LoicHa** [comment]
You can insert image in the footer/header if you use a Base64 image inline

IE 👍 

`<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />`

The colors are working too but it seems that you can't use the color : white ,  because you can't apply any css background in the footer or header... that's very unfortunate
