### ISSUE TITLE
Use of custom PKI

### ISSUE THREAD

**Issue by babs** [thecodingmachine/gotenberg#76]
We are using gotenberg internally against https servers with certificates generated with an internal PKI.

As I usually do for other images, I made a new dockerimage based on `thecodingmachine/gotenberg:5`

```docker
FROM thecodingmachine/gotenberg:5

ADD http://blahblahblah/internal-pki.crt /usr/local/share/ca-certificates/internal-pki.crt
RUN set -xeu \
  && update-ca-certificates

```

The certificate is properly deployed, rehashed, symlinked and added to ca-certificates.crt and it works with curl, wget and so on.
This is usually enough for being taken in consideration by all our ecosystem including servers and chrome etc on workstations. 

Here, it doesn't work. Any clues ?

More generally, it seems that when there is a certificate issue (self signed, unrecognized authority, name issue etc) we only got blank page, without anymore info in the logs :/
Please note that it works like a charm using a commonly accepted Root CA.

**Comment by gulien** [comment]
Hello @babs! 

I'm not familiar with "custom certificate management" (not sure about the wording lol) so I'm afraid I may not be able to help that much.

That's said, there is maybe an option to launch Google Chrome in order to skip certificate issue (see https://github.com/thecodingmachine/gotenberg/blob/master/internal/pkg/pm2/chrome.go#L34).

**Comment by babs** [comment]
I found a solution.

It seems that Chrome in this case uses `~/.pki/nnsdb` as reference and but only creates it at the first start.
My workaround is to create the folder at build time and initialize it. Only then inject my Root CA inside.
At this point everything works.

Here is an example of Dockerfile that mitigate the issue.

```docker
FROM thecodingmachine/gotenberg:5

ADD http://blahblahblah/internal-pki.crt /usr/local/share/ca-certificates/internal-pki.crt
RUN set -xeu \
  && update-ca-certificates \
  && apt-get update && apt-get -y libnss3-tools \
  && mkdir -p /root/.pki/nssdb \
  && certutil -d sql:/root/.pki/nssdb -N --empty-password \
  && certutil -d sql:/root/.pki/nssdb -A -t TC -n CorpAuthority -i /usr/local/share/ca-certificates/internal-pki.crt

```

**Comment by gulien** [comment]
👍 glad you find a solution!
