### ISSUE TITLE
How do I set the margins when I convert excel

### ISSUE THREAD

**Issue by zjfjiayou** [thecodingmachine/gotenberg#79]
## Expected Behavior
Convert Xlsx file to a PDF file

## Current Behavior
I want to control the margins of the PDF output

## Your Environment

* Version used: 5
* Operating System and version: macos mojave 10.14.1
* Link to your project:

**Comment by gulien** [comment]
Currently you cannot do it directly with the API.
Also, there are no options for this purpose in `unoconv` (the underlying tool used for this kind of conversion).

That's said, you may try something like this: https://github.com/unoconv/unoconv/issues/208#issuecomment-52926813

**Comment by zjfjiayou** [comment]
Thanks
