### ISSUE TITLE
V5.0  template?

### ISSUE THREAD

**Issue by lsaint** [thecodingmachine/gotenberg#80]
I have been using V2.0 for a long time,  there was a gotenberg.yml which can  set custom command (eg.  change unoconv args).  But i can't find the corresponding setting in V5.0？  

So my question is how can i change the unoconv args in V5.0?

**Comment by gulien** [comment]
Hello @lsaint!

Short answer: it disappeared since v3.

What's your need? 😄

**Comment by lsaint** [comment]
Thanks for the reply.   In our scenario,  we need to output another format by unoconv sometimes, in v2 i can change it easily. Since we don't have the `gotenberg.yml ` anymore,  and i haven't read all the v5's code yet, maybe you can give some advise to me about how to implement it.

**Comment by lsaint** [comment]
plus,  i didn't find doc about how to build from source in v5.

**Comment by gulien** [comment]
Here the file you're looking for: https://github.com/thecodingmachine/gotenberg/blob/master/internal/pkg/printer/office.go.

For building the image, check the Makefile: https://github.com/thecodingmachine/gotenberg/blob/master/Makefile.

**Comment by lsaint** [comment]
Thanks a lot, I'll give it a shot.
