### ISSUE TITLE
Authentification to the remote URL

### ISSUE THREAD

**Issue by PYBurosse** [thecodingmachine/gotenberg#81]
Is there a way to add an authentification key to the header of the request send by the gotenberg API when it fetch the web page specified in the remoteURL parameter ?

I need to create a pdf from an app page that isn't publicly accessible, so I'd like to authorize the gotenberg API to access, without adding the authentification in the URL, that wouldn't be very secured.

Is there a way to do that that I missed in the documentation, or is anything like this planned for a future version ?

**Comment by gulien** [comment]
Indeed having the option to set custom headers for remoteURL (and webhook) make sense!

**Comment by PYBurosse** [comment]
That would be great and that would help us a lot, thank you for your answer

**Comment by Pierstoval** [comment]
Besides authentication, a solution could be a simple "headers" option that would allow us to provide whatever HTTP header to send to the remote url. This could be used for authentication.

**Comment by bgentry** [comment]
Definitely would love the option to send any header to the remote URL. I plan to use this for `Authorization` initially but there could be others. Seems like it'd be easiest to just have a single option that allows you to add any header to the outgoing request.

**Comment by anak-tnk** [comment]
@gulien Hi.. It seems that the custom header you provided is not working for a remoteURL.  Would be great if you could look at this. 

AD
