### ISSUE TITLE
Whether the pagerange parameter can be added to specify the print range

### ISSUE THREAD

**Issue by zjfjiayou** [thecodingmachine/gotenberg#84]
I have a requirement for preview, which will get stuck when converting large files. I hope you can add such a parameter to speed up the conversion. Thank you

**Comment by gulien** [comment]
Hello @zjfjiayou!

Great idea!

**Comment by zjfjiayou** [comment]
Thank you very much. Hope to get it out soon

**Comment by gulien** [comment]
I'm currently quite busy, but once I got some free time I'll check it for sure.
