### ISSUE TITLE
Disk space leak

### ISSUE THREAD

**Issue by JWillow** [thecodingmachine/gotenberg#87]
Hello,

I remark an issue about the space disk. When a timeout occurs, the process is stopped but the workdir inside the container isn't clear.

**Comment by gulien** [comment]
By timeout, do you mean the API response (504)? 

If so, it should be cleared as I've create a handler for that: https://github.com/thecodingmachine/gotenberg/blob/master/internal/app/api/middleware.go#L44

**Comment by guanchaoli** [comment]
> I had the code response 500 with this message
> 
> `{"time":"2019-06-12T07:46:09.073828582Z","id":"","remote_ip":"172.17.0.1","host":"10.0.2.4:8091","method":"POST","uri":"/convert/office","user_agent":"Java/1.8.0_212","status":500,"error":"code=500, message=unoconv: signal: killed","latency":10119491393,"latency_human":"10.119491393s","bytes_in":3083918,"bytes_out":38}`
> 
> After that I discover the parameter _waitTimeout_, I give 20 (more than the default (10)) and the conversion process finished properly.
> 
> When I had the code 500, the document still stored inside the container.

Could you tell me how to add this waitTimeout parameter?
