### ISSUE TITLE
Very slow POST request to gotenberg to convert html -> pdf

### ISSUE THREAD

**Issue by Przemek625** [thecodingmachine/gotenberg#89]
I noticed that sending the post request with file that has 150 344 bytes is  slow. In my local enviroment I takes about 4 sec to get the Response. In my production enviroment I takes about 40 sec! We use python request library and we send just the attached file to the server. Do we need to use some extrat options to zip the html file or sth?

**Comment by gulien** [comment]
Hello @Przemek625 

It shouldn't be slow. It might be:
* a network issue
* not enough RAM or CPU allowed

**Comment by Przemek625** [comment]
@gulien could you tell me how much time it takes in your local and production env to generator pdf?

**Comment by gulien** [comment]
On MacOS (not the best OS for Docker performance), generating a PDF from [those files](https://github.com/thecodingmachine/gotenberg/tree/master/test/testdata/html) takes less than 1 secondes (something like 200ms).

**Comment by Przemek625** [comment]
@gulien in my local ubuntu, with 30gb ram and i5 it takes 4sec from request start to response using curl like in docs you said

**Comment by JWillow** [comment]
Hello Przemek625,
We enter in a complicated discussion because we need to know exactly your configuration, the process started, etc ...

Nonetheless, it's not pejorative, but Gotenberg is just a simple great :) wrapper around openoffice/libreoffice. Can you convert a document to a pdf directly in command line `soffice --headless --convert-to pdf somefile.txt`

pejorative

**Comment by gulien** [comment]
@JWillow actually @Przemek625 is using the HTML to PDF feature 😄

**Comment by JWillow** [comment]
Sorry, all were in the title!

**Comment by Przemek625** [comment]
```
curl --request POST \
    --url http://localhost:3000/convert/html \
    --header 'Content-Type: multipart/form-data' \
    --form files=@index.html \
    -o result2.pdf

```
![image](https://user-images.githubusercontent.com/15988345/59878198-f920ab00-93a7-11e9-89cf-60a9d27f67e7.png)

Is this normal for localhost?

**Comment by JWillow** [comment]
If you use the file index.html provide by gulien it weight is 2.66 KB and your output seems to be 13.8MB.
Do you have open the result2.pdf ? is it well formed?

**Comment by Przemek625** [comment]
@JWIlow file ja perfectly formatted

**Comment by JWillow** [comment]
![image](https://user-images.githubusercontent.com/88036/59880858-5cadd700-93ae-11e9-89dd-3bf8b8d4425f.png)

less one second

**Comment by JWillow** [comment]
In the output of the container you have also measure. For me :+1: 
![image](https://user-images.githubusercontent.com/88036/59881038-e2318700-93ae-11e9-8a0b-ce10c9507e8b.png)

**Comment by Przemek625** [comment]
I noticed that my HTML that has about  150kb generates 15mb pdf. It contains images. But those downloaded images weight 2mb.

**Comment by gulien** [comment]
@Przemek625 please reopen if you still have this issue with the newer version of Gotenberg.

**Comment by lavrenkov-sketch** [comment]
@Przemek625 could you share the implementation of reading about submitting a document in python
