### ISSUE TITLE
Anyone tried this on Cloudrun? GCP.

### ISSUE THREAD

**Issue by andrewmclagan** [thecodingmachine/gotenberg#90]
> Cloud Run is a managed compute platform that automatically scales your stateless containers. Cloud Run is serverless: it abstracts away all infrastructure management, so you can focus on what matters most — building great applications

Anyone tried Gotenberg on Cloudrun? Im assuming it would work as its stateless? Could have huge cost savings...

**Comment by gulien** [comment]
@andrewmclagan Looks like AWS Fargate, but simpler 🤔

**Comment by odarriba** [comment]
We are using it, for testing purposes and we can say it definitively works well! We maintain a fork so we could add authentication (maybe a PR would be welcome on the official repo for this?).

We can say it works well, except for the first Office conversion request, which returns an error code. Subsequent calls work as expected 🔥

**Comment by gulien** [comment]
@odarriba thank you very much of this feedback!

>  except for the first Office conversion request, which returns an error code

Even with version 6?

**Comment by odarriba** [comment]
Yesterday I tested version 6 on Google Cloud Run (a custom build with the code from #128 ) but I couldn't make it work.

It said that:

```
Application failed to start: Failed to create init process: Failed to load /tini: permission denied
```

While on my laptop it works, so I suppose this is some kind of issue related to Cloud Run and it's execution environment.

**Comment by gulien** [comment]
Weird. Need to deep to dive to Cloud Run in order to understand what's going on. Might be user related.

**Comment by twgraham** [comment]
Tried myself with version 6, same result. Is tini being executed from an unprivileged user?

**Comment by twgraham** [comment]
So changing the owner of `tini` to gotenberg fixed it.

i.e.
```bash
ADD --chown=gotenberg https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini /tini
```

Not really familiar with `tini`, but is there a reason against this?

**Comment by gulien** [comment]
Thanks @twgraham 

Not sure why it works without this fix on another platform though 🤔... Less permissive environment on CloudRun?

Could you open a PR @twgraham ?

**Comment by tobwen** [comment]
Sorry for offtopic, but - wow - the prices of GCR are really interesting. Perhaps I'm using the calculator wrong, but if not, this is great.

**Comment by gulien** [comment]
> except for the first Office conversion request, which returns an error code

Hey @odarriba, could you tell me if this issue is still happening with latest version?

**Comment by benze** [comment]
> We can say it works well, except for the first Office conversion request, which returns an error code. Subsequent calls work as expected 🔥

I'm investigating if/how to run this in something like Fargate, but I don't follow/understand how to configure it to stop after it is done processing.  How did you configure to shut down automatically after finishing a conversion?  Or after a given idle time?

**Comment by Henribou** [comment]
> > except for the first Office conversion request, which returns an error code
> 
> Hey @odarriba, could you tell me if this issue is still happening with latest version? Thank you 😄

Hello @gulien,
I tried with the latest version but it didn't work, I needed to change the owner of `tini` in the Dockerfile (as show by @twgraham , thank you by the way). If you are interested, I can give you all the command line necessary to deploy it on GCR (for the future users).

**Comment by gulien** [comment]
@Henribou 

See https://github.com/thecodingmachine/gotenberg/issues/221#issuecomment-651644035 :)

**Comment by Jackojack7** [comment]
I am trying to deploy the gotenberg container on Cloud run but still get the `tini` ownership error.
Some can add some explanation how to resolve this?

**Comment by ekeuus** [comment]
> > I am trying to deploy the gotenberg container on Cloud run but still get the `tini` ownership error.
> > Someone can please add some explanation how to resolve this?
> 
> For those new to Docker/Cloud run as myself, here are the steps to make this work:
> 
> 1. Fork this repository.
> 2. Edit the file `/build/package/Dockerfile` changing the following line
> 
> From:
> 
> ```
> ADD https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static /tini
> ```
> 
> To:
> 
> ```
> ADD --chown=gotenberg https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static /tini
> ```
> 
> 1. On the project path run `make image` to rebuild it with the new configuration.
> 2. Use docker to tag the new image and push it to cloud run.
> 3. Enjoy!

Thanks! Ideally would be nice to have it resolved by the maintainer tho?

**Comment by gulien** [comment]
@ekeuus 

See https://github.com/thecodingmachine/gotenberg/issues/221#issuecomment-651644035 :)

**Comment by ekeuus** [comment]
Why is the chown causing issues for non-Cloud Run use causes or what is the vulnerability? Sorry for the naive question.

**Comment by gulien** [comment]
With security issues you never know 😄

**Comment by adetiamarhadi** [comment]
> We are using it, for testing purposes and we can say it definitively works well! We maintain a fork so we could add authentication (maybe a PR would be welcome on the official repo for this?).
> 
> We can say it works well, except for the first Office conversion request, which returns an error code. Subsequent calls work as expected 🔥

hi, which version do you use on google cloud run? because I have an issue when using the latest version

**Comment by janswist** [comment]
https://github.com/janswist/gotenberg/blob/main/build/Dockerfile.cloudrun seems like it should work out of the box, but it's not. Still getting Tini error on Cloud Run

**Comment by janswist** [comment]
https://github.com/gotenberg/gotenberg/blob/main/build/Dockerfile.cloudrun
seems like it should work out of the box, but it's not. Still getting Tini error on Cloud Run

Getting this error: 
`terminated: Application failed to start: Failed to create init process: failed to load /usr/bin/tini: exec format error`
