### ISSUE TITLE
waitDelay required for loading google fonts

### ISSUE THREAD

**Issue by bernhardmiller** [thecodingmachine/gotenberg#92]
Hello,

I'm starting to use gotenberg in one of my projects, and really like it so far! However, I came across some weird behavior that I think is a bug:

## Expected Behavior
I'm rendering a simple html page like this one, that uses a font from Google Fonts:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Titel</title>

    <style>
body {
    font-family: "Source Sans Pro", sans-serif;
    font-size: 10pt;
    background: white !important;
    color: black; !important;
}
    </style>

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
</head>
<body>
    <h1>Titel</h1>
</body>
</html>
```
I expect the h1 text to be visible in the rendered pdf document.

## Current Behavior
The h1 text is not visible in the pdf.
I also don't see it when using txt2pdf.

## Possible Solution
It seems to work if I add the waitDelay option with a value >= 1. However, I'm really worried about adding a guessed value as hard-coded timeout in production...
If I change the css to not use Source Sans Pro, everything is rendered fine.

## Steps to Reproduce (for bugs)
1. Make the above html available through some URL
2. Call gotenberg's convert/url function through curl without a waitDelay parameter
3. Check the returned pdf - there is no text

## Your Environment

* Version used: 5
* Operating System and version: Ubuntu 18.04

## Other observations
It appears to me that the page is somehow rendered before the downloaded font is processed. It is weird, however, that the rendering fails consistently with a waitDelay value of 0.9, and works 100% of the time with a value of 1.0

**Comment by gulien** [comment]
Hello @bernhardmiller

Indeed looks like a bug... You should not have to use the `waitDelay` option; it is mainly for pages which are mostly rendered with JavaScript.

I'm [watching](https://github.com/thecodingmachine/gotenberg/blob/master/internal/pkg/printer/chrome.go#L79) some events to "guess" if the page is ready to be generated. For instance, I'm watching the network to make sure that all assets are downloaded (Google fonts etc.). If one or more events have not be fired before the `waitTimeout` duration (10 seconds by default), the generation will be considered to be unsuccessful.

**Comment by Przemek625** [comment]
I would like to report that we encounted similiar issue. Some parts of generated pdf are not visible. We also use google fonts in our html.

**Comment by bernhardmiller** [comment]
As a side note, there is maybe also an int/float issue. I've never used go, so please forgive the clumsy style:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	dur := 0.9
	fmt.Println(dur)
	fmt.Println(time.Second)
	fmt.Println(time.Duration(dur) * time.Second)
}
```

prints
```
0.9
1s
0s
```

So that at least explains the 100% hit rate with waiting 1 second vs waiting 0.9 seconds :)

**Comment by gulien** [comment]
Good catch! That idea also hit me as I was trying to understand why 0.9 vs 1 makes a huge difference in your case 😄

**Comment by Przemek625** [comment]
@gulien When you guys are going to fix this? Because I noticef that my pdfs miss content all the time in production enviroment.

**Comment by gulien** [comment]
@Przemek625 the version 6 is currently in development (on my free time) and there are others improvements / bugs fix coming. Can't tell when it will be available.

Currently, you may use the `waitDelay` option as a workaround.
