### ISSUE TITLE
Memory usage constantly increasing

### ISSUE THREAD

**Issue by bendavies** [thecodingmachine/gotenberg#96]
Hey there,

We're experiencing an issue with Gotenberg where by the memory usage is constantly increasing over time, up to a point that it is being killed by the container orchestrator, ECS in this instance.
Here's a graph of gotenbergs memory usage over time.
![image](https://user-images.githubusercontent.com/625392/60920453-21594680-a290-11e9-9b21-aaac7bd5b51b.png)

The large drops are ECS killing the container when the memory limit is reached. (the last restart is a manual one by me)
We've given the container 512MB of memory in this example.

Have you experienced this behaviour yourselves?
Is 512MB sufficient? (We used 512MB as it is in the docs as a 'production' config)
Is there a possible memory leak somewhere?

Many thanks in advance!

## Your Environment
* Version used: 5.1.0
* Operating System and version: vendor provided docker image.

**Comment by gulien** [comment]
Hello @bendavies 

Are you only using Google Chrome or do you use LibreOffice too?
Do you have some healthchecks going on?

**Comment by bendavies** [comment]
hi @gulien! 
just google chrome! 
Yes, we are using the healthcheck. it's being hit every 30 seconds.

**Comment by bendavies** [comment]
i would say there is possible a small problem with the healthcheck, and also a problem while generating pdfs.
![image](https://user-images.githubusercontent.com/625392/60962649-a41ce880-a306-11e9-9b7f-08040591888d.png)


if you look at the start of that graph, only the healthcheck is being hit, but memory is increasing. then, once pdf generation starts, memory increases more rapidly.

**Comment by gulien** [comment]
I'm pretty sure the issue comes from Google Chrome. It might be one or both of the following:

- Google Chrome itself has a memory leak
- The interactions between Gotenberg and Google Chrome

Could you try to increase the memory? For instance to 1GB?

**Comment by gulien** [comment]
Hey @compleatang! Does it happens too in your Kubernetes cluster ?

**Comment by bendavies** [comment]
@gulien we can certainly give it more memory to see what happens

**Comment by bendavies** [comment]
We've given it a 1G now, so will report back in a few days

**Comment by gulien** [comment]
@bendavies any news?

**Comment by rodnaph** [comment]
@gulien We are still seeing the memory climb until the process crashes. We will try #103 when a fix is available.

**Comment by gulien** [comment]
Thank you @rodnaph 

I'll try to fix this issue in the version 6.0.0. 
You'll find more details about what's going on here: https://github.com/mafredri/cdp/issues/101

**Comment by bendavies** [comment]
thanks - we'll give it a go!

**Comment by bendavies** [comment]
this is looking a lot better now.
![image](https://user-images.githubusercontent.com/625392/66331026-87a24380-e929-11e9-97ff-fac4bf4c549c.png)


Memory is still increasing, but very gradually.

**Comment by gulien** [comment]
@bendavies thank you for the feedback 👍 not sure if I can do more though. Does your instance handles a lot of conversions?
