### ISSUE TITLE
HTML Convert Request Timeout

### ISSUE THREAD

**Issue by lukichev** [thecodingmachine/gotenberg#98]
## Current Behavior
After some time html convert stops working and throwing this error: 
`{"time":"2019-07-22T14:53:34.662611739Z","id":"","remote_ip":"10.36.1.90","host":"gotenberg:3000","method":"POST","uri":"/convert/html","user_agent":"","status":408,"error":"code=408, message=Request Timeout","latency":12699612585,"latency_human":"12.699612585s","bytes_in":1980,"bytes_out":30}`

##  Expected Behavior
Gotenberg should probably auto heal somehow if this happens. 
We think that Chromium is going down for some reason. Maybe because of memory.

**Comment by gulien** [comment]
Might be related to #103

**Comment by gulien** [comment]
Might be related to #96

**Comment by gulien** [comment]
Thank you @lukichev  

I'll try to fix this issue in the version 6.0.0. 
You'll find more details about what's going on here: https://github.com/mafredri/cdp/issues/101
